//! Content-addressed clipboard store.
//!
//! Invention. Every terminal implements OSC 52 as "set the system
//! clipboard to this string" — the payload vanishes into the OS
//! clipboard layer and becomes indistinguishable from whatever
//! else the user copied. `ClipboardStore` keeps a **session-local**
//! mirror of every OSC 52 payload mado sees, indexed by BLAKE3-128
//! hash of its content. That hash becomes a stable token the
//! clipboard payload can be referenced by after the fact:
//!
//!   1. Shell runs `printf '\e]52;c;<base64>\e\\'`.
//!   2. mado parses OSC 52, decodes base64, stores into
//!      `ClipboardStore` → gets back a `ClipboardHash`.
//!   3. mado emits that hash via an MCP tool (planned) so escriba
//!      (or any other typed client) can fetch the payload back
//!      by hash — **after** the OS clipboard has rotated on to
//!      a different copy.
//!
//! No editor category member exposes clipboard content-addressing.
//! Alacritty / iTerm2 / ghostty all forget the payload the moment
//! OSC 52 runs. Mado keeps the whole session's scrollback-of-
//! clipboards, letting workflows (escriba `defworkflow` steps, LLM
//! tools, scripts) quote and attest specific copies.
//!
//! # Semantics
//!
//! - **Idempotent** — storing the same content twice returns the
//!   same hash; the `set_at` timestamp refreshes to the latest
//!   write so LRU rotation reflects *most recent use*.
//! - **Capacity-bounded** — default 128 entries, oldest evicted
//!   first. Session-scoped; clearing is the implicit reset when
//!   the terminal exits.
//! - **Hash size = 128 bits** — 16 bytes of BLAKE3 output. More
//!   than enough for session uniqueness; keeps tokens short in
//!   MCP payloads (32 hex chars).

use std::collections::{HashMap, VecDeque};

use image::ImageEncoder;
use pleme_kindstr_derive::KindStr;

/// 16-byte (128-bit) BLAKE3-prefix hash. Content-addressed
/// identifiers for clipboard payloads. `to_hex()` is the canonical
/// serialization for MCP wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ClipboardHash([u8; 16]);

impl ClipboardHash {
    /// Compute the hash of `content`. Stable across sessions: same
    /// bytes in → same hash out. Short-prefix (16 bytes) collision
    /// risk is ~2^-64 for typical clipboard workloads; cheaper than
    /// the full 32-byte output at MCP-payload sizes.
    #[must_use]
    pub fn of(content: &str) -> Self {
        let full = blake3::hash(content.as_bytes());
        let mut short = [0u8; 16];
        short.copy_from_slice(&full.as_bytes()[..16]);
        Self(short)
    }

    /// 32-char lowercase hex encoding. The canonical wire form.
    #[must_use]
    pub fn to_hex(self) -> String {
        let mut out = String::with_capacity(32);
        for byte in self.0 {
            use std::fmt::Write as _;
            let _ = write!(out, "{byte:02x}");
        }
        out
    }

    /// Parse a 32-char hex string back into a hash. Returns `None`
    /// for anything else (wrong length, non-hex chars).
    #[must_use]
    pub fn from_hex(s: &str) -> Option<Self> {
        if s.len() != 32 {
            return None;
        }
        let mut out = [0u8; 16];
        for (i, byte) in out.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).ok()?;
        }
        Some(Self(out))
    }
}

/// Which OSC 52 "selection buffer" the payload targets. Vim /
/// emacs / tmux / ghostty all support these three; mado records
/// them so escriba workflows can say "give me the last *primary*
/// selection" rather than just "the last copy".
///
/// The single-char label round-trip ([`Self::from_str_kind`] ↔
/// [`Self::as_str`]) is generated by `#[derive(KindStr)]` (the
/// macro-farm paired round-trip derive) from the per-variant
/// `#[kind(name = "...", alias = "...")]` attrs — one authored label
/// table instead of two hand-kept inverse match arms. The uppercase
/// OSC-52 spellings (`P` / `S`) are repeatable `alias` entries.
/// The slice-taking, System-defaulting [`Self::from_osc52_byte`]
/// below is a thin wrapper preserving mado's OSC-52 parse signature.
#[derive(Debug, Clone, Copy, PartialEq, Eq, KindStr)]
pub enum ClipboardKind {
    /// `c` — the system clipboard. Default.
    #[kind(name = "c")]
    System,
    /// `p` — the primary (X11 middle-click) selection.
    #[kind(name = "p", alias = "P")]
    Primary,
    /// `s` — secondary; rare but standards-compliant.
    #[kind(name = "s", alias = "S")]
    Secondary,
}

impl ClipboardKind {
    /// Decode an OSC 52 kind byte. Defaults to [`System`](Self::System)
    /// for unrecognised / empty values. Thin wrapper over the derived
    /// [`Self::from_str_kind`] — OSC-52 selection bytes are ASCII, so
    /// we interpret the slice as a string and fall back to the system
    /// clipboard when it doesn't match a known label (matches ghostty's
    /// permissive parse).
    #[must_use]
    pub fn from_osc52_byte(b: &[u8]) -> Self {
        std::str::from_utf8(b)
            .ok()
            .and_then(Self::from_str_kind)
            .unwrap_or(Self::System)
    }
}

/// One remembered clipboard copy.
#[derive(Debug, Clone)]
pub struct ClipboardEntry {
    pub hash: ClipboardHash,
    pub content: String,
    pub kind: ClipboardKind,
    /// Wall-clock-like monotonic timestamp — used purely for LRU
    /// ordering. We count `store()` invocations (not wall time) so
    /// tests stay deterministic and the type stays `no_std`-clean.
    pub set_at: u64,
}

/// Bounded LRU-eviction clipboard store, content-addressed.
#[derive(Debug)]
pub struct ClipboardStore {
    entries: HashMap<ClipboardHash, ClipboardEntry>,
    /// Insertion/access order; oldest at the front, most recent at
    /// the back. Eviction pops the front.
    order: VecDeque<ClipboardHash>,
    capacity: usize,
    /// Monotonic counter used as the `set_at` stamp.
    tick: u64,
}

impl ClipboardStore {
    /// New empty store bounded by `capacity` entries.
    #[must_use]
    pub fn new(capacity: usize) -> Self {
        Self {
            entries: HashMap::new(),
            order: VecDeque::new(),
            capacity: capacity.max(1),
            tick: 0,
        }
    }

    /// Store `content` under its BLAKE3-prefix hash. Idempotent —
    /// calling twice with the same bytes returns the same hash,
    /// refreshes the LRU position, and updates `set_at`. Evicts
    /// the oldest entry if the store is at capacity and this is a
    /// fresh insert.
    pub fn store(&mut self, content: String, kind: ClipboardKind) -> ClipboardHash {
        let hash = ClipboardHash::of(&content);
        self.tick += 1;
        let already_present = self.entries.contains_key(&hash);
        if already_present {
            // Move to back of order — most recent.
            self.order.retain(|h| *h != hash);
        } else if self.entries.len() >= self.capacity {
            if let Some(oldest) = self.order.pop_front() {
                self.entries.remove(&oldest);
            }
        }
        self.order.push_back(hash);
        self.entries.insert(
            hash,
            ClipboardEntry {
                hash,
                content,
                kind,
                set_at: self.tick,
            },
        );
        hash
    }

    /// Look up an entry by hash.
    #[must_use]
    pub fn get(&self, hash: ClipboardHash) -> Option<&ClipboardEntry> {
        self.entries.get(&hash)
    }

    /// Entries in most-recent-first order. The contract MCP tools
    /// that surface "clipboard history" consume.
    pub fn entries_recent_first(&self) -> impl Iterator<Item = &ClipboardEntry> {
        self.order.iter().rev().filter_map(|h| self.entries.get(h))
    }

    /// Count currently stored entries.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// True when empty.
    #[must_use]
    #[allow(dead_code)] // Idiomatic alongside `len()`; consumed by tests + future IPC.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Cheap membership probe — `true` when `hash` is currently
    /// indexed. Used by the MCP `clipboard_put` tool to tell the
    /// caller "this payload was already in the store" without
    /// cloning the entry.
    #[must_use]
    pub fn contains(&self, hash: ClipboardHash) -> bool {
        self.entries.contains_key(&hash)
    }

    /// Drop every entry. Returns the number of entries that were
    /// removed. Used by the MCP `clipboard_clear` tool when an
    /// escriba workflow wants to scrub the session's copy history
    /// (e.g., after touching credentials / secrets).
    pub fn clear(&mut self) -> usize {
        let n = self.entries.len();
        self.entries.clear();
        self.order.clear();
        // Keep `tick` monotonic — don't reset it. LRU ordering after
        // clear starts fresh from the current tick value, which
        // keeps later `store()` calls strictly greater than any
        // future-referencing external consumer (rare, but cheap to
        // preserve).
        n
    }
}

/// PasteGuard — strip bytes that would let pasted content break out of
/// (or fake) bracketed-paste framing: the classic paste-injection
/// vector where a malicious clipboard ends the bracket early and the
/// rest executes as keystrokes.
///
/// * `bracketed`: remove every occurrence of the terminator
///   `ESC[201~` — the only sequence with framing power inside a
///   bracketed paste; everything else arrives as inert text.
/// * unbracketed: remove ESC outright — without framing, ANY escape
///   byte executes in the application as if typed.
///
/// Both paste sites (local-PTY `main.rs` and tear-attach
/// `gui_tear_attach.rs`) route through this one function.
#[must_use]
pub fn sanitize_paste(text: &str, bracketed: bool) -> Vec<u8> {
    if bracketed {
        const END: &[u8] = b"\x1b[201~";
        let mut out = text.as_bytes().to_vec();
        while let Some(pos) = out.windows(END.len()).position(|w| w == END) {
            out.drain(pos..pos + END.len());
        }
        out
    } else {
        // Non-bracketed: the receiving app reads the paste as typed
        // keystrokes, and Enter is CR (0x0D) — normalize CRLF and
        // bare LF to CR like xterm/kitty/ghostty, or CRLF-sourced
        // text executes each line plus a spurious empty accept-line
        // and LF-only text misfires in raw-mode REPLs. ESC stripped
        // for the injection floor.
        let mut out = Vec::with_capacity(text.len());
        let bytes = text.as_bytes();
        let mut i = 0;
        while i < bytes.len() {
            match bytes[i] {
                0x1b => {}
                b'\r' if i + 1 < bytes.len() && bytes[i + 1] == b'\n' => {
                    out.push(b'\r');
                    i += 1;
                }
                b'\n' => out.push(b'\r'),
                b => out.push(b),
            }
            i += 1;
        }
        out
    }
}

// ── Clipboard image paste (ghostty parity) ──────────────────────────
//
// OSC 52 is text-only — it has no MIME concept and cannot carry image
// bytes. So a terminal bridges a clipboard IMAGE through the filesystem
// exactly like ghostty does: encode it to a PNG in `$TMPDIR` and paste
// the *path*, which file-loading TUIs (Claude Code, `$EDITOR`) then read
// back. hasami owns reading the raw RGBA off the system clipboard
// (`ClipboardProvider::paste_image`); this owns the terminal-side policy
// of materializing it into a pasteable file.

/// How long a clipboard-image temp PNG lives before the next image paste
/// reaps it. Matches ghostty's 24h retention — long enough that a pasted
/// path stays valid across a work session, short enough that `$TMPDIR`
/// doesn't accumulate screenshots forever.
const CLIPBOARD_PNG_MAX_AGE: std::time::Duration = std::time::Duration::from_secs(24 * 60 * 60);

/// Filename prefix for mado's clipboard-image temp PNGs. Owned (not the
/// bare `clipboard-` ghostty uses) so the reaper only ever deletes
/// mado's OWN files, never a sibling terminal's temp images.
const CLIPBOARD_PNG_PREFIX: &str = "mado-clip-";

/// Errors materializing a clipboard image into a pasteable temp PNG.
#[derive(Debug, thiserror::Error)]
pub enum ClipboardImageError {
    /// The clipboard image carried no pixels.
    #[error("clipboard image is empty")]
    Empty,
    /// `rgba.len()` did not match `width * height * 4`.
    #[error("rgba buffer is {got} bytes, expected {expected} for {width}x{height}")]
    SizeMismatch {
        width: u32,
        height: u32,
        expected: usize,
        got: usize,
    },
    /// PNG encoding failed.
    #[error("png encode failed: {0}")]
    Encode(String),
    /// Writing the temp file failed.
    #[error("write temp png failed: {0}")]
    Write(#[from] std::io::Error),
}

/// Encode a raw RGBA8 clipboard image to PNG, write it to a temp file in
/// `$TMPDIR`, and return the path — the bytes a terminal pastes so a
/// file-loading TUI receives the image. The ghostty image-paste contract.
///
/// Best-effort reaps mado's own stale clipboard PNGs (older than
/// [`CLIPBOARD_PNG_MAX_AGE`]) first so `$TMPDIR` can't grow without
/// bound; a reap failure never blocks the paste.
///
/// # Errors
///
/// [`ClipboardImageError::Empty`] for a zero-sized image,
/// [`ClipboardImageError::SizeMismatch`] when `rgba` isn't exactly
/// `width * height * 4` bytes, [`ClipboardImageError::Encode`] on a PNG
/// failure, and [`ClipboardImageError::Write`] if the temp file can't be
/// written.
pub fn write_clipboard_png(
    width: u32,
    height: u32,
    rgba: &[u8],
) -> Result<std::path::PathBuf, ClipboardImageError> {
    if width == 0 || height == 0 || rgba.is_empty() {
        return Err(ClipboardImageError::Empty);
    }
    let expected = (width as usize)
        .checked_mul(height as usize)
        .and_then(|px| px.checked_mul(4))
        .ok_or(ClipboardImageError::SizeMismatch {
            width,
            height,
            expected: usize::MAX,
            got: rgba.len(),
        })?;
    if rgba.len() != expected {
        return Err(ClipboardImageError::SizeMismatch {
            width,
            height,
            expected,
            got: rgba.len(),
        });
    }

    let mut png: Vec<u8> = Vec::new();
    image::codecs::png::PngEncoder::new(&mut png)
        .write_image(rgba, width, height, image::ExtendedColorType::Rgba8)
        .map_err(|e| ClipboardImageError::Encode(e.to_string()))?;

    let dir = std::env::temp_dir();
    reap_stale_clipboard_pngs(&dir, CLIPBOARD_PNG_MAX_AGE);
    let path = dir.join(clipboard_png_filename());
    std::fs::write(&path, &png)?;
    tracing::debug!(path = %path.display(), bytes = png.len(), "wrote clipboard image to temp png");
    Ok(path)
}

/// `mado-clip-<unix_nanos>-<pid>.png` — unique per write without an RNG
/// dependency (nanosecond clock + pid don't collide within a process).
fn clipboard_png_filename() -> String {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{CLIPBOARD_PNG_PREFIX}{nanos}-{}.png", std::process::id())
}

/// Best-effort delete of mado's own clipboard PNGs older than `max_age`.
/// Never errors — a paste must not fail because a stale temp file
/// couldn't be reaped (permissions, a racing reaper, a vanished dir).
fn reap_stale_clipboard_pngs(dir: &std::path::Path, max_age: std::time::Duration) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let now = std::time::SystemTime::now();
    for entry in entries.flatten() {
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        if !(name.starts_with(CLIPBOARD_PNG_PREFIX) && name.ends_with(".png")) {
            continue;
        }
        let stale = entry
            .metadata()
            .and_then(|m| m.modified())
            .ok()
            .and_then(|mtime| now.duration_since(mtime).ok())
            .is_some_and(|age| age > max_age);
        if stale {
            let _ = std::fs::remove_file(entry.path());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- PasteGuard ----

    #[test]
    fn sanitize_paste_passes_plain_text_through() {
        // Bracketed: byte-faithful (the app unwraps the frame itself).
        assert_eq!(sanitize_paste("hello world\n", true), b"hello world\n");
        // Non-bracketed: line ends are keystrokes — Enter is CR.
        assert_eq!(sanitize_paste("hello world\n", false), b"hello world\r");
    }

    #[test]
    fn sanitize_paste_normalizes_line_ends_when_unbracketed() {
        assert_eq!(sanitize_paste("a\r\nb\nc\r", false), b"a\rb\rc\r");
        // Bracketed leaves them alone.
        assert_eq!(sanitize_paste("a\r\nb\n", true), b"a\r\nb\n");
    }

    #[test]
    fn sanitize_paste_strips_bracket_terminator_when_bracketed() {
        // The injection: paste ends the bracket early, then `rm -rf`+CR
        // would execute as typed keystrokes.
        let evil = "innocent\x1b[201~rm -rf /\r";
        let safe = sanitize_paste(evil, true);
        assert_eq!(safe, b"innocentrm -rf /\r");
        assert!(!safe.windows(6).any(|w| w == b"\x1b[201~"));
    }

    #[test]
    fn sanitize_paste_strips_interleaved_terminators() {
        // Terminator split so removal of one occurrence must not
        // reassemble another: ESC[201 + ESC[201~ + ~ — after removing
        // the inner full terminator the outer halves join up and must
        // ALSO be removed (the while-loop re-scan).
        let evil = "\x1b[201\x1b[201~~payload";
        let safe = sanitize_paste(evil, true);
        assert!(
            !safe.windows(6).any(|w| w == b"\x1b[201~"),
            "reassembled terminator survived: {safe:?}"
        );
    }

    #[test]
    fn sanitize_paste_strips_esc_when_unbracketed() {
        let evil = "ok\x1b[31mred\x1b]0;title\x07";
        let safe = sanitize_paste(evil, false);
        assert!(!safe.contains(&0x1b), "ESC survived unbracketed paste");
        assert_eq!(safe, b"ok[31mred]0;title\x07");
    }

    #[test]
    fn hash_is_stable_across_calls() {
        let a = ClipboardHash::of("hello world");
        let b = ClipboardHash::of("hello world");
        assert_eq!(a, b);
    }

    #[test]
    fn different_content_gives_different_hash() {
        let a = ClipboardHash::of("one");
        let b = ClipboardHash::of("two");
        assert_ne!(a, b);
    }

    #[test]
    fn hash_round_trips_through_hex() {
        let h = ClipboardHash::of("payload");
        let hex = h.to_hex();
        assert_eq!(hex.len(), 32);
        assert_eq!(ClipboardHash::from_hex(&hex), Some(h));
    }

    #[test]
    fn hash_from_hex_rejects_malformed() {
        assert!(ClipboardHash::from_hex("too-short").is_none());
        assert!(ClipboardHash::from_hex(&"zz".repeat(16)).is_none());
    }

    #[test]
    fn kind_decoder_handles_canonical_bytes() {
        assert_eq!(ClipboardKind::from_osc52_byte(b"c"), ClipboardKind::System);
        assert_eq!(ClipboardKind::from_osc52_byte(b"p"), ClipboardKind::Primary);
        assert_eq!(
            ClipboardKind::from_osc52_byte(b"s"),
            ClipboardKind::Secondary
        );
        // Unknown → fallback to System (matches ghostty's permissive
        // parse; users who care about precision set `c` explicitly).
        assert_eq!(ClipboardKind::from_osc52_byte(b""), ClipboardKind::System);
        assert_eq!(ClipboardKind::from_osc52_byte(b"x"), ClipboardKind::System);
    }

    #[test]
    fn store_is_idempotent_on_same_content() {
        let mut store = ClipboardStore::new(16);
        let h1 = store.store("payload".into(), ClipboardKind::System);
        let h2 = store.store("payload".into(), ClipboardKind::System);
        assert_eq!(h1, h2);
        assert_eq!(store.len(), 1);
    }

    #[test]
    fn store_lru_evicts_oldest_first() {
        let mut store = ClipboardStore::new(2);
        let h_a = store.store("A".into(), ClipboardKind::System);
        let h_b = store.store("B".into(), ClipboardKind::System);
        let h_c = store.store("C".into(), ClipboardKind::System);
        assert_eq!(store.len(), 2);
        // A was oldest — evicted.
        assert!(store.get(h_a).is_none());
        assert!(store.get(h_b).is_some());
        assert!(store.get(h_c).is_some());
    }

    #[test]
    fn store_restore_moves_entry_to_back() {
        // Re-storing an existing hash bumps its LRU position — the
        // next eviction should skip it.
        let mut store = ClipboardStore::new(2);
        let h_a = store.store("A".into(), ClipboardKind::System);
        let _h_b = store.store("B".into(), ClipboardKind::System);
        // Re-touch A so it's most-recent.
        let _h_a2 = store.store("A".into(), ClipboardKind::System);
        // Fresh insert C evicts B (not A).
        let h_c = store.store("C".into(), ClipboardKind::System);
        assert!(store.get(h_a).is_some());
        assert!(store.get(h_c).is_some());
    }

    #[test]
    fn entries_recent_first_yields_newest_first() {
        let mut store = ClipboardStore::new(16);
        store.store("first".into(), ClipboardKind::System);
        store.store("second".into(), ClipboardKind::System);
        store.store("third".into(), ClipboardKind::System);
        let contents: Vec<String> = store
            .entries_recent_first()
            .map(|e| e.content.clone())
            .collect();
        assert_eq!(contents, vec!["third", "second", "first"]);
    }

    #[test]
    fn store_tracks_kind_per_entry() {
        let mut store = ClipboardStore::new(16);
        let h = store.store("x".into(), ClipboardKind::Primary);
        let entry = store.get(h).unwrap();
        assert_eq!(entry.kind, ClipboardKind::Primary);
        assert_eq!(entry.kind.as_str(), "p");
    }

    #[test]
    fn contains_probes_without_cloning() {
        let mut store = ClipboardStore::new(4);
        let h = store.store("present".into(), ClipboardKind::System);
        assert!(store.contains(h));
        let missing = ClipboardHash::of("not-in-store");
        assert!(!store.contains(missing));
    }

    #[test]
    fn clear_returns_prior_len_and_wipes_both_indexes() {
        let mut store = ClipboardStore::new(8);
        store.store("a".into(), ClipboardKind::System);
        store.store("b".into(), ClipboardKind::System);
        store.store("c".into(), ClipboardKind::System);
        assert_eq!(store.len(), 3);
        let cleared = store.clear();
        assert_eq!(cleared, 3);
        assert!(store.is_empty());
        // After clear, a fresh store() still works — tick stayed
        // monotonic so new entries are strictly more recent.
        let h = store.store("d".into(), ClipboardKind::System);
        assert_eq!(store.len(), 1);
        assert!(store.contains(h));
    }

    #[test]
    fn clear_on_empty_store_returns_zero() {
        let mut store = ClipboardStore::new(4);
        assert_eq!(store.clear(), 0);
    }

    // ---- clipboard image paste ----

    #[test]
    fn write_clipboard_png_roundtrips_a_2x2_image() {
        // 2×2 RGBA: red, green / blue, white.
        let rgba = vec![
            255, 0, 0, 255, 0, 255, 0, 255, //
            0, 0, 255, 255, 255, 255, 255, 255,
        ];
        let path = write_clipboard_png(2, 2, &rgba).expect("write temp png");
        assert!(path.exists(), "temp png materialized");
        assert!(
            path.file_name()
                .unwrap()
                .to_str()
                .unwrap()
                .starts_with("mado-clip-"),
            "owned prefix so the reaper only touches mado's files"
        );
        // It is a real, decodable PNG of the right size — the file a
        // pasted path points at is loadable by the receiving TUI.
        let bytes = std::fs::read(&path).unwrap();
        let img =
            image::load_from_memory_with_format(&bytes, image::ImageFormat::Png).expect("decode");
        assert_eq!((img.width(), img.height()), (2, 2));
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn write_clipboard_png_rejects_size_mismatch() {
        // 2×2 needs 16 RGBA bytes; 8 is short → typed SizeMismatch, not
        // a panic or a corrupt file.
        let err = write_clipboard_png(2, 2, &[0u8; 8]).unwrap_err();
        assert!(matches!(
            err,
            ClipboardImageError::SizeMismatch {
                expected: 16,
                got: 8,
                ..
            }
        ));
    }

    #[test]
    fn write_clipboard_png_rejects_empty() {
        assert!(matches!(
            write_clipboard_png(0, 0, &[]).unwrap_err(),
            ClipboardImageError::Empty
        ));
    }

    #[test]
    fn reap_targets_only_mados_own_stale_pngs() {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir =
            std::env::temp_dir().join(format!("mado-reap-test-{}-{nanos}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let mine = dir.join("mado-clip-1-2.png");
        let foreign = dir.join("clipboard-other.png"); // ghostty's prefix
        let nonpng = dir.join("mado-clip-note.txt");
        for f in [&mine, &foreign, &nonpng] {
            std::fs::write(f, b"x").unwrap();
        }
        // max_age ZERO ⇒ every existing file is "stale"; only mado's own
        // *.png is eligible. Proves the prefix+extension filter.
        reap_stale_clipboard_pngs(&dir, std::time::Duration::ZERO);
        assert!(!mine.exists(), "mado's own stale png reaped");
        assert!(
            foreign.exists(),
            "a sibling terminal's png is never touched"
        );
        assert!(nonpng.exists(), "a non-png mado file is never touched");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
