//! Keybinding system — configurable key -> action mapping via awase.
//!
//! Uses `awase::Hotkey` and `awase::Binding` for key binding definitions,
//! providing a consistent hotkey representation across pleme-io apps.
//! Default keybindings use macOS-style Cmd as the primary modifier.

use pleme_kindstr_derive::KindStr;
use serde::{Deserialize, Serialize};

/// High-level terminal actions triggered by keybindings.
///
/// The config-name round-trip ([`Self::from_str_kind`] ↔
/// [`Self::as_str`]) is generated by `#[derive(KindStr)]` (the
/// macro-farm paired round-trip derive) from the per-variant
/// `#[kind(name = "...", alias = "...")]` attrs — one authored
/// action-name table instead of the hand-written `parse_action`
/// match. The canonical `name` is the serde snake_case spelling
/// (so `as_str` agrees with serde); the legacy / colon-form / verb-
/// order config spellings ride along as repeatable `alias`es.
/// The Phase-4-removed multiplexing spellings (`new_tab`,
/// `goto_split:next`, …) carry no `name`/`alias`, so `from_str_kind`
/// returns `None` for them — preserving `parse_action`'s "recognised
/// but no longer dispatched" behaviour.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, KindStr)]
#[serde(rename_all = "snake_case")]
pub enum Action {
    #[kind(name = "copy")]
    Copy,
    #[kind(name = "paste")]
    Paste,
    #[kind(name = "paste_from_selection")]
    PasteFromSelection,
    #[kind(name = "scroll_up")]
    ScrollUp,
    #[kind(name = "scroll_down")]
    ScrollDown,
    #[kind(name = "scroll_page_up")]
    ScrollPageUp,
    #[kind(name = "scroll_page_down")]
    ScrollPageDown,
    #[kind(name = "scroll_to_top")]
    ScrollToTop,
    #[kind(name = "scroll_to_bottom")]
    ScrollToBottom,
    #[kind(name = "jump_to_prompt")]
    JumpToPrompt,
    #[kind(name = "jump_to_prompt_prev", alias = "jump_to_prompt:prev", alias = "jump_to_previous_prompt")]
    JumpToPromptPrev,
    #[kind(name = "jump_to_prompt_next", alias = "jump_to_prompt:next", alias = "jump_to_next_prompt")]
    JumpToPromptNext,
    #[kind(name = "search_open", alias = "search")]
    SearchOpen,
    #[kind(name = "search_close")]
    SearchClose,
    #[kind(name = "search_next")]
    SearchNext,
    #[kind(name = "search_prev")]
    SearchPrev,
    #[kind(name = "font_increase", alias = "increase_font_size")]
    FontIncrease,
    #[kind(name = "font_decrease", alias = "decrease_font_size")]
    FontDecrease,
    #[kind(name = "font_reset", alias = "reset_font_size")]
    FontReset,
    // NewTab / CloseTab / NextTab / PrevTab / SplitHorizontal /
    // SplitVertical / FocusNext / FocusPrev / ClosePane removed
    // at Phase 4 — multiplexing lives in tear, not mado. See
    // theory/MADO-TEAR-M5.md. Users who want splits / tabs run
    // tear inside mado (or use `mado tear-attach --gpu`).
    #[kind(name = "reset_terminal", alias = "reset")]
    ResetTerminal,
    #[kind(name = "clear_screen")]
    ClearScreen,
    #[kind(name = "toggle_fullscreen")]
    ToggleFullscreen,
    #[kind(name = "select_all")]
    SelectAll,
    #[kind(name = "copy_url_to_clipboard")]
    CopyUrlToClipboard,
    #[kind(name = "toggle_mouse_reporting")]
    ToggleMouseReporting,
}

/// A keybinding mapping an awase hotkey to a mado action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Keybinding {
    pub hotkey: awase::Hotkey,
    pub action: Action,
}

/// Keybinding manager with lookup.
pub struct KeybindManager {
    bindings: Vec<Keybinding>,
}

#[allow(dead_code)]
impl KeybindManager {
    /// Create with platform-appropriate default bindings.
    /// Construct an EMPTY KeybindManager — zero bindings, every
    /// keystroke falls through to the PTY by default. Operator
    /// principle: nothing is bound until explicitly opted in.
    ///
    /// For mado's curated baseline (Cmd-+/Cmd--/Cmd-0/Cmd-C/...)
    /// call [`KeybindManager::with_mado_defaults`] instead. That
    /// constructor IS the documented "default mado experience" —
    /// `new()` is for headless paths, tests, and operators who
    /// want to start from scratch.
    #[must_use]
    pub fn new() -> Self {
        Self {
            bindings: Vec::new(),
        }
    }

    /// Construct a KeybindManager pre-populated with mado's curated
    /// baseline (`default_bindings()`). This is what `main.rs` +
    /// `gui_tear_attach.rs` call so operators get a useful first-
    /// launch experience without writing a yaml file.
    ///
    /// Each binding can be removed via [`KeybindManager::unbind`]
    /// or replaced via [`KeybindManager::bind`]; the operator-
    /// visible set is `manager.bindings()`.
    #[must_use]
    pub fn with_mado_defaults() -> Self {
        Self {
            bindings: default_bindings(),
        }
    }

    /// Look up an action for the given awase hotkey.
    #[must_use]
    pub fn lookup(&self, hotkey: &awase::Hotkey) -> Option<Action> {
        self.bindings
            .iter()
            .find(|b| b.hotkey == *hotkey)
            .map(|b| b.action)
    }

    /// Look up an action using awase key + modifier components.
    #[must_use]
    pub fn lookup_key(&self, key: awase::Key, modifiers: awase::Modifiers) -> Option<Action> {
        let hotkey = awase::Hotkey::new(modifiers, key);
        self.lookup(&hotkey)
    }

    /// Add or replace a keybinding using an awase hotkey.
    pub fn bind(&mut self, hotkey: awase::Hotkey, action: Action) {
        self.bindings.retain(|b| b.hotkey != hotkey);
        self.bindings.push(Keybinding { hotkey, action });
    }

    /// Add or replace a keybinding parsed from a string (e.g., "cmd+c").
    pub fn bind_str(&mut self, hotkey_str: &str, action: Action) -> Result<(), awase::AwaseError> {
        let hotkey = awase::Hotkey::parse(hotkey_str)?;
        self.bind(hotkey, action);
        Ok(())
    }

    /// Remove a keybinding for the given hotkey.
    pub fn unbind(&mut self, hotkey: &awase::Hotkey) {
        self.bindings.retain(|b| b.hotkey != *hotkey);
    }

    /// All current bindings.
    #[must_use]
    pub fn bindings(&self) -> &[Keybinding] {
        &self.bindings
    }

    /// Convenience: look up an action directly from a madori
    /// KeyEvent. Encapsulates the modifier → awase + key → awase
    /// conversion so the tear-attach event loop (which doesn't
    /// pull main.rs's helpers) can dispatch keybindings the same
    /// way the local-PTY path does.
    ///
    /// Returns `None` when the key + modifiers don't match a
    /// bound action — caller falls back to forwarding the text
    /// to the PTY (or dropping it if a non-text modifier is held).
    #[must_use]
    pub fn lookup_madori(&self, event: &madori::event::KeyEvent) -> Option<Action> {
        let key = madori_key_to_awase(&event.key, &event.text)?;
        let mods = madori_modifiers_to_awase(event.modifiers);
        self.lookup(&awase::Hotkey::new(mods, key))
    }
}

/// Convert a madori::Modifiers to awase::Modifiers. Shared by
/// main.rs (local-PTY path) and gui_tear_attach.rs (tear path)
/// so both use the same modifier rules. `meta` (winit's term for
/// macOS Cmd) maps to `awase::Modifiers::CMD`.
#[must_use]
pub fn madori_modifiers_to_awase(m: madori::event::Modifiers) -> awase::Modifiers {
    let mut out = awase::Modifiers::NONE;
    if m.ctrl {
        out = out | awase::Modifiers::CTRL;
    }
    if m.alt {
        out = out | awase::Modifiers::ALT;
    }
    if m.shift {
        out = out | awase::Modifiers::SHIFT;
    }
    if m.meta {
        out = out | awase::Modifiers::CMD;
    }
    out
}

/// Convert a madori::KeyCode + optional text into an awase::Key.
/// Returns None for keys with no awase equivalent (e.g. unknown
/// scancode, multi-char text).
#[must_use]
pub fn madori_key_to_awase(
    key: &madori::event::KeyCode,
    text: &Option<String>,
) -> Option<awase::Key> {
    match key {
        madori::event::KeyCode::Enter => Some(awase::Key::Return),
        madori::event::KeyCode::Escape => Some(awase::Key::Escape),
        madori::event::KeyCode::Tab => Some(awase::Key::Tab),
        madori::event::KeyCode::Backspace => Some(awase::Key::Backspace),
        madori::event::KeyCode::Delete => Some(awase::Key::Delete),
        madori::event::KeyCode::Home => Some(awase::Key::Home),
        madori::event::KeyCode::End => Some(awase::Key::End),
        madori::event::KeyCode::PageUp => Some(awase::Key::PageUp),
        madori::event::KeyCode::PageDown => Some(awase::Key::PageDown),
        madori::event::KeyCode::Up => Some(awase::Key::Up),
        madori::event::KeyCode::Down => Some(awase::Key::Down),
        madori::event::KeyCode::Left => Some(awase::Key::Left),
        madori::event::KeyCode::Right => Some(awase::Key::Right),
        madori::event::KeyCode::F(n) => match n {
            1 => Some(awase::Key::F1),
            2 => Some(awase::Key::F2),
            3 => Some(awase::Key::F3),
            4 => Some(awase::Key::F4),
            5 => Some(awase::Key::F5),
            6 => Some(awase::Key::F6),
            7 => Some(awase::Key::F7),
            8 => Some(awase::Key::F8),
            9 => Some(awase::Key::F9),
            10 => Some(awase::Key::F10),
            11 => Some(awase::Key::F11),
            12 => Some(awase::Key::F12),
            _ => None,
        },
        madori::event::KeyCode::Char(ch) => char_to_awase_key(*ch),
        madori::event::KeyCode::Space => Some(awase::Key::Space),
        _ => {
            // Try to extract from text (e.g. shifted symbols).
            if let Some(t) = text {
                if let Some(ch) = t.chars().next() {
                    if t.len() == ch.len_utf8() {
                        return char_to_awase_key(ch);
                    }
                }
            }
            None
        }
    }
}

/// Lowercase-folded char → awase::Key. Centralizes the
/// printable-to-key map both event paths use.
#[must_use]
pub fn char_to_awase_key(ch: char) -> Option<awase::Key> {
    match ch.to_ascii_lowercase() {
        'a' => Some(awase::Key::A),
        'b' => Some(awase::Key::B),
        'c' => Some(awase::Key::C),
        'd' => Some(awase::Key::D),
        'e' => Some(awase::Key::E),
        'f' => Some(awase::Key::F),
        'g' => Some(awase::Key::G),
        'h' => Some(awase::Key::H),
        'i' => Some(awase::Key::I),
        'j' => Some(awase::Key::J),
        'k' => Some(awase::Key::K),
        'l' => Some(awase::Key::L),
        'm' => Some(awase::Key::M),
        'n' => Some(awase::Key::N),
        'o' => Some(awase::Key::O),
        'p' => Some(awase::Key::P),
        'q' => Some(awase::Key::Q),
        'r' => Some(awase::Key::R),
        's' => Some(awase::Key::S),
        't' => Some(awase::Key::T),
        'u' => Some(awase::Key::U),
        'v' => Some(awase::Key::V),
        'w' => Some(awase::Key::W),
        'x' => Some(awase::Key::X),
        'y' => Some(awase::Key::Y),
        'z' => Some(awase::Key::Z),
        '0' => Some(awase::Key::Num0),
        '1' => Some(awase::Key::Num1),
        '2' => Some(awase::Key::Num2),
        '3' => Some(awase::Key::Num3),
        '4' => Some(awase::Key::Num4),
        '5' => Some(awase::Key::Num5),
        '6' => Some(awase::Key::Num6),
        '7' => Some(awase::Key::Num7),
        '8' => Some(awase::Key::Num8),
        '9' => Some(awase::Key::Num9),
        ' ' => Some(awase::Key::Space),
        '/' => Some(awase::Key::Slash),
        '+' | '=' => Some(awase::Key::Equal),
        '-' => Some(awase::Key::Minus),
        ',' => Some(awase::Key::Comma),
        '.' => Some(awase::Key::Period),
        _ => None,
    }
}

impl Default for KeybindManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Encode a cursor key under the active DECCKM mode.
///
/// `application_mode = true` → `ESC O <ch>` (DECCKM set, mode `?1h`).
/// `application_mode = false` → `ESC [ <ch>` (DECCKM reset, default).
///
/// `ch` is the trailing letter for the sequence:
/// `b'A'` Up, `b'B'` Down, `b'C'` Right, `b'D'` Left, `b'H'` Home,
/// `b'F'` End.
#[must_use]
pub fn cursor_key_bytes(ch: u8, application_mode: bool) -> Vec<u8> {
    if application_mode {
        vec![0x1b, b'O', ch]
    } else {
        vec![0x1b, b'[', ch]
    }
}

/// Encode an F1–F12 keystroke as the xterm-canonical escape sequence.
/// Returns an empty `Vec` for `n` outside `1..=12` to match the
/// legacy `main.rs` helper this consolidates.
#[must_use]
pub fn f_key_escape(n: u8) -> Vec<u8> {
    match n {
        1 => b"\x1bOP".to_vec(),
        2 => b"\x1bOQ".to_vec(),
        3 => b"\x1bOR".to_vec(),
        4 => b"\x1bOS".to_vec(),
        5 => b"\x1b[15~".to_vec(),
        6 => b"\x1b[17~".to_vec(),
        7 => b"\x1b[18~".to_vec(),
        8 => b"\x1b[19~".to_vec(),
        9 => b"\x1b[20~".to_vec(),
        10 => b"\x1b[21~".to_vec(),
        11 => b"\x1b[23~".to_vec(),
        12 => b"\x1b[24~".to_vec(),
        _ => vec![],
    }
}

/// Translate a madori `KeyEvent` (key + text + modifiers) into the
/// raw PTY byte sequence the running shell expects.
///
/// **Single source of truth** for the legacy `main.rs` path and the
/// embedded-tear `gui_tear_attach.rs` path. Prior to consolidation
/// these two paths had divergent logic — the tear path silently
/// dropped every `Ctrl+letter` keystroke (including `Ctrl-R`, which
/// killed atuin/skim history search). See the dedicated regression
/// test `ctrl_r_produces_0x12_via_helper` below — that one exists
/// to prevent the regression.
///
/// Returns:
/// - `Some(bytes)` when the keystroke maps to PTY bytes.
/// - `None` when the keystroke has no PTY translation — caller
///   decides whether to drop it (bare Cmd + no matching binding)
///   or ignore it (e.g. modifier-only keystroke).
///
/// `app_cursor_mode` is the active DECCKM state for the destination
/// terminal. Pass `false` for the embedded-tear path until tear-core
/// gains DECCKM tracking.
#[must_use]
pub fn madori_key_to_pty_bytes(
    key: &madori::event::KeyCode,
    text: &Option<String>,
    modifiers: madori::event::Modifiers,
    app_cursor_mode: bool,
) -> Option<Vec<u8>> {
    // Cmd-only (no Ctrl, no Alt) with no matching keybinding is a
    // GUI shortcut, not PTY input. Caller drops.
    if modifiers.meta && !modifiers.ctrl && !modifiers.alt {
        return None;
    }

    if let Some(t) = text {
        if !t.is_empty() {
            if modifiers.ctrl && t.len() == 1 {
                let ch = t.chars().next().unwrap();
                if ch.is_ascii_alphabetic() {
                    let ctrl_byte = (ch.to_ascii_lowercase() as u8) - b'a' + 1;
                    return Some(vec![ctrl_byte]);
                }
            }
            if modifiers.alt {
                let mut bytes = vec![0x1b];
                bytes.extend_from_slice(t.as_bytes());
                return Some(bytes);
            }
            return Some(t.as_bytes().to_vec());
        }
    }

    if modifiers.ctrl {
        if let madori::event::KeyCode::Char(ch) = key {
            if ch.is_ascii_alphabetic() {
                let ctrl_byte = (ch.to_ascii_lowercase() as u8) - b'a' + 1;
                return Some(vec![ctrl_byte]);
            }
        }
    }

    if modifiers.alt {
        if let madori::event::KeyCode::Char(ch) = key {
            let mut bytes = vec![0x1b];
            let mut buf = [0u8; 4];
            bytes.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());
            return Some(bytes);
        }
    }

    match key {
        madori::event::KeyCode::Enter => Some(b"\r".to_vec()),
        madori::event::KeyCode::Backspace => Some(b"\x7f".to_vec()),
        madori::event::KeyCode::Tab => Some(b"\t".to_vec()),
        madori::event::KeyCode::Escape => Some(b"\x1b".to_vec()),
        madori::event::KeyCode::Space => Some(b" ".to_vec()),
        madori::event::KeyCode::Up => Some(cursor_key_bytes(b'A', app_cursor_mode)),
        madori::event::KeyCode::Down => Some(cursor_key_bytes(b'B', app_cursor_mode)),
        madori::event::KeyCode::Right => Some(cursor_key_bytes(b'C', app_cursor_mode)),
        madori::event::KeyCode::Left => Some(cursor_key_bytes(b'D', app_cursor_mode)),
        madori::event::KeyCode::Home => Some(cursor_key_bytes(b'H', app_cursor_mode)),
        madori::event::KeyCode::End => Some(cursor_key_bytes(b'F', app_cursor_mode)),
        madori::event::KeyCode::Delete => Some(b"\x1b[3~".to_vec()),
        madori::event::KeyCode::PageUp => Some(b"\x1b[5~".to_vec()),
        madori::event::KeyCode::PageDown => Some(b"\x1b[6~".to_vec()),
        madori::event::KeyCode::F(n) => Some(f_key_escape(*n)),
        _ => None,
    }
}

/// Parse an action name from config into an [`Action`]. Thin wrapper
/// over the derived [`Action::from_str_kind`] — the canonical names +
/// aliases live on the per-variant `#[kind(...)]` attrs. The
/// Phase-4-removed multiplexing spellings (`new_tab`, `close_tab`,
/// `split_horizontal`, `goto_split:next`, `close_surface`, …) carry no
/// `#[kind]` entry, so they fall through to `None` exactly as before —
/// "recognised in legacy configs but no longer dispatched."
pub fn parse_action(name: &str) -> Option<Action> {
    Action::from_str_kind(name)
}

/// Helper to create a binding from an awase hotkey.
fn hk(modifiers: awase::Modifiers, key: awase::Key) -> awase::Hotkey {
    awase::Hotkey::new(modifiers, key)
}

/// Default keybindings (macOS-style: Cmd as primary modifier).
fn default_bindings() -> Vec<Keybinding> {
    use awase::atlas_chord;
    use awase::Key;
    use awase::Modifiers;

    // Atlas-resolved chords — every cross-GUI-terminal binding pulls
    // its chord from `ishou_tokens::FleetKeybinds::prescribed()` via
    // `awase::atlas_chord!`. The macro stringifies the field name as
    // the panic label so an atlas drift names the offending intent
    // automatically. Guard convergence test in `tests::mado_default
    // _bindings_converge_with_fleet_atlas` pins the mapping.
    let kb = ishou_tokens::FleetKeybinds::prescribed();

    // App-specific chords NOT in the atlas (mado-only ergonomics +
    // OSC-133 prompt navigation + scroll keys). These stay
    // hand-wired until the atlas earns a third consumer for each.
    let cmd = Modifiers::CMD;
    let cmd_shift = Modifiers::CMD | Modifiers::SHIFT;
    let none = Modifiers::NONE;

    vec![
        // Clipboard — atlas-sourced.
        Keybinding { hotkey: atlas_chord!(kb.copy),  action: Action::Copy },
        Keybinding { hotkey: atlas_chord!(kb.paste), action: Action::Paste },
        // Search — atlas-sourced.
        Keybinding { hotkey: atlas_chord!(kb.search_open),  action: Action::SearchOpen },
        Keybinding { hotkey: atlas_chord!(kb.search_close), action: Action::SearchClose },
        Keybinding { hotkey: atlas_chord!(kb.search_next),  action: Action::SearchNext },
        Keybinding { hotkey: atlas_chord!(kb.search_prev),  action: Action::SearchPrev },
        // Font — atlas-sourced.
        Keybinding { hotkey: atlas_chord!(kb.font_increase), action: Action::FontIncrease },
        Keybinding { hotkey: atlas_chord!(kb.font_decrease), action: Action::FontDecrease },
        Keybinding { hotkey: atlas_chord!(kb.font_reset),    action: Action::FontReset },
        // Fullscreen — atlas-sourced.
        Keybinding { hotkey: atlas_chord!(kb.toggle_fullscreen), action: Action::ToggleFullscreen },
        // Scroll — mado-specific (no atlas intent yet).
        Keybinding { hotkey: hk(none, Key::PageUp),   action: Action::ScrollPageUp },
        Keybinding { hotkey: hk(none, Key::PageDown), action: Action::ScrollPageDown },
        Keybinding { hotkey: hk(cmd,  Key::Home),     action: Action::ScrollToTop },
        Keybinding { hotkey: hk(cmd,  Key::End),      action: Action::ScrollToBottom },
        // Prompt navigation — ghostty-canonical Cmd+Up / Cmd+Down on
        // OSC 133 prompt marks. Requires the shell integration scripts
        // (see shell-integration/mado.*) to be sourced. mado-specific.
        Keybinding { hotkey: hk(cmd, Key::Up),   action: Action::JumpToPromptPrev },
        Keybinding { hotkey: hk(cmd, Key::Down), action: Action::JumpToPromptNext },
        // Terminal — mado-specific (no atlas reset intent).
        Keybinding { hotkey: hk(cmd_shift, Key::R), action: Action::ResetTerminal },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_is_empty() {
        // Operator principle: zero bindings until explicitly opted in.
        let mgr = KeybindManager::new();
        assert!(mgr.bindings().is_empty());
    }

    #[test]
    fn with_mado_defaults_populates_baseline() {
        let mgr = KeybindManager::with_mado_defaults();
        assert!(!mgr.bindings().is_empty());
        // Sanity-check the canonical font-zoom triplet is present.
        let cmd = awase::Modifiers::CMD;
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::Equal)),
            Some(Action::FontIncrease)
        );
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::Minus)),
            Some(Action::FontDecrease)
        );
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::Num0)),
            Some(Action::FontReset)
        );
    }

    #[test]
    fn mado_default_bindings_converge_with_fleet_atlas() {
        // The 10 atlas-sourced chords in `default_bindings()` must
        // round-trip through `awase::Hotkey::parse_atlas_chord` and
        // match the chord declared in `ishou_tokens::FleetKeybinds::
        // prescribed()`. Drift in either layer (atlas changes a
        // chord, or mado's default_bindings starts hand-coding again)
        // fails this Guard chain loudly rather than at operator-press
        // time.
        let mgr = KeybindManager::with_mado_defaults();
        let kb = ishou_tokens::FleetKeybinds::prescribed();

        // For each (intent, expected action), the binding manager
        // must return that action when looked up with the
        // atlas-parsed hotkey.
        let atlas_actions: &[(&str, Action)] = &[
            (kb.copy,              Action::Copy),
            (kb.paste,             Action::Paste),
            (kb.search_open,       Action::SearchOpen),
            (kb.search_close,      Action::SearchClose),
            (kb.search_next,       Action::SearchNext),
            (kb.search_prev,       Action::SearchPrev),
            (kb.font_increase,     Action::FontIncrease),
            (kb.font_decrease,     Action::FontDecrease),
            (kb.font_reset,        Action::FontReset),
            (kb.toggle_fullscreen, Action::ToggleFullscreen),
        ];
        for (chord, expected) in atlas_actions {
            let hk = awase::Hotkey::parse_atlas_chord(chord)
                .unwrap_or_else(|e| panic!("atlas chord {chord:?} parse failed: {e}"));
            assert_eq!(
                mgr.lookup(&hk),
                Some(*expected),
                "mado default for atlas chord {chord:?} does not bind {expected:?}",
            );
        }

        // Symmetric Guard assertion via ishou's typed convergence
        // helper. Catches the same drift class but with the named-
        // intent error message ("font_increase chord drift") rather
        // than the action-lookup mismatch above.
        ishou_tokens::convergence::Guard::for_app("mado")
            .expect_copy(kb.copy)
            .expect_paste(kb.paste)
            .expect_search_open(kb.search_open)
            .expect_search_close(kb.search_close)
            .expect_search_next(kb.search_next)
            .expect_search_prev(kb.search_prev)
            .expect_font_increase(kb.font_increase)
            .expect_font_decrease(kb.font_decrease)
            .expect_font_reset(kb.font_reset)
            .expect_toggle_fullscreen(kb.toggle_fullscreen)
            .run();
    }

    #[test]
    fn lookup_copy() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::C);
        assert_eq!(mgr.lookup(&hk), Some(Action::Copy));
    }

    #[test]
    fn lookup_paste() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::V);
        assert_eq!(mgr.lookup(&hk), Some(Action::Paste));
    }

    #[test]
    fn lookup_no_match() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::X);
        assert_eq!(mgr.lookup(&hk), None);
    }

    #[test]
    fn custom_binding() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CTRL, awase::Key::R);
        mgr.bind(hk, Action::ResetTerminal);
        assert_eq!(mgr.lookup(&hk), Some(Action::ResetTerminal));
    }

    #[test]
    fn unbind() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::C);
        assert!(mgr.lookup(&hk).is_some());
        mgr.unbind(&hk);
        assert!(mgr.lookup(&hk).is_none());
    }

    #[test]
    fn rebind_replaces() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::C);
        mgr.bind(hk, Action::ResetTerminal);
        assert_eq!(mgr.lookup(&hk), Some(Action::ResetTerminal));
    }

    #[test]
    fn lookup_key_works() {
        let mgr = KeybindManager::with_mado_defaults();
        let action = mgr.lookup_key(awase::Key::C, awase::Modifiers::CMD);
        assert_eq!(action, Some(Action::Copy));
    }

    #[test]
    fn search_bindings() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk_open = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::F);
        assert_eq!(mgr.lookup(&hk_open), Some(Action::SearchOpen));

        let hk_close = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::Escape);
        assert_eq!(mgr.lookup(&hk_close), Some(Action::SearchClose));
    }

    #[test]
    fn bind_str_valid() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let result = mgr.bind_str("cmd+t", Action::Copy);
        assert!(result.is_ok());
        let hk = awase::Hotkey::parse("cmd+t").unwrap();
        assert_eq!(mgr.lookup(&hk), Some(Action::Copy));
    }

    #[test]
    fn bind_str_invalid() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let result = mgr.bind_str("not_a_real_hotkey!!!", Action::Copy);
        assert!(result.is_err());
    }

    #[test]
    fn default_bindings_count() {
        let mgr = KeybindManager::with_mado_defaults();
        // Default bindings after Phase 4 (multiplexing actions
        // removed): clipboard (2) + search (4) + font (3) +
        // scroll (4) + prompt jump (2) + terminal (1) + fullscreen
        // (1) = 17.
        assert_eq!(mgr.bindings().len(), 17);
    }

    #[test]
    fn all_actions_serializable() {
        let actions = [
            Action::Copy, Action::Paste, Action::PasteFromSelection,
            Action::ScrollUp, Action::ScrollDown,
            Action::ScrollPageUp, Action::ScrollPageDown, Action::ScrollToTop,
            Action::ScrollToBottom, Action::JumpToPrompt,
            Action::JumpToPromptPrev, Action::JumpToPromptNext,
            Action::SearchOpen, Action::SearchClose,
            Action::SearchNext, Action::SearchPrev, Action::FontIncrease,
            Action::FontDecrease, Action::FontReset,
            Action::ResetTerminal,
            Action::ClearScreen, Action::ToggleFullscreen, Action::SelectAll,
            Action::CopyUrlToClipboard, Action::ToggleMouseReporting,
        ];
        for action in &actions {
            let json = serde_json::to_string(action);
            assert!(json.is_ok(), "Failed to serialize {:?}", action);
            let json_str = json.unwrap();
            let parsed: Result<Action, _> = serde_json::from_str(&json_str);
            assert!(parsed.is_ok(), "Failed to deserialize {:?}", action);
            assert_eq!(*action, parsed.unwrap());
        }
    }

    #[test]
    fn test_scroll_page_up_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::PageUp);
        assert_eq!(mgr.lookup(&hk), Some(Action::ScrollPageUp));
    }

    #[test]
    fn test_scroll_page_down_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::PageDown);
        assert_eq!(mgr.lookup(&hk), Some(Action::ScrollPageDown));
    }

    // test_focus_next_binding / test_focus_prev_binding /
    // test_close_pane_binding removed at Phase 4 — the actions
    // they exercised no longer exist; mado is single-pane now.

    #[test]
    fn test_toggle_fullscreen_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::CTRL,
            awase::Key::F,
        );
        assert_eq!(mgr.lookup(&hk), Some(Action::ToggleFullscreen));
    }

    #[test]
    fn test_reset_terminal_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::SHIFT,
            awase::Key::R,
        );
        assert_eq!(mgr.lookup(&hk), Some(Action::ResetTerminal));
    }

    #[test]
    fn test_total_default_bindings_count() {
        let mgr = KeybindManager::with_mado_defaults();
        assert_eq!(mgr.bindings().len(), 17);
    }

    #[test]
    fn test_parse_action_known() {
        assert_eq!(parse_action("copy"), Some(Action::Copy));
        assert_eq!(parse_action("paste"), Some(Action::Paste));
        assert_eq!(parse_action("paste_from_selection"), Some(Action::PasteFromSelection));
        assert_eq!(parse_action("scroll_to_top"), Some(Action::ScrollToTop));
        assert_eq!(parse_action("jump_to_prompt"), Some(Action::JumpToPrompt));
        assert_eq!(parse_action("clear_screen"), Some(Action::ClearScreen));
        assert_eq!(parse_action("select_all"), Some(Action::SelectAll));
        assert_eq!(parse_action("copy_url_to_clipboard"), Some(Action::CopyUrlToClipboard));
        assert_eq!(parse_action("toggle_mouse_reporting"), Some(Action::ToggleMouseReporting));
    }

    #[test]
    fn test_parse_action_aliases() {
        assert_eq!(parse_action("search"), Some(Action::SearchOpen));
        assert_eq!(parse_action("increase_font_size"), Some(Action::FontIncrease));
        assert_eq!(parse_action("decrease_font_size"), Some(Action::FontDecrease));
        assert_eq!(parse_action("reset_font_size"), Some(Action::FontReset));
        // Phase 4 — goto_split:* / close_surface resolve to None
        // (multiplexing belongs in tear).
        assert_eq!(parse_action("goto_split:next"), None);
        assert_eq!(parse_action("goto_split:previous"), None);
        assert_eq!(parse_action("close_surface"), None);
        assert_eq!(parse_action("reset"), Some(Action::ResetTerminal));
    }

    #[test]
    fn test_parse_action_unknown() {
        assert_eq!(parse_action("not_a_real_action"), None);
        assert_eq!(parse_action(""), None);
    }

    #[test]
    fn action_canonical_name_round_trips() {
        // Pin the derived as_str ↔ from_str_kind inverse: every
        // action's canonical name parses back to itself. Catches a
        // drifted #[kind(name = …)] that no longer agrees with the
        // serde snake_case spelling parse_action delegates to.
        let actions = [
            Action::Copy, Action::Paste, Action::PasteFromSelection,
            Action::ScrollUp, Action::ScrollDown,
            Action::ScrollPageUp, Action::ScrollPageDown, Action::ScrollToTop,
            Action::ScrollToBottom, Action::JumpToPrompt,
            Action::JumpToPromptPrev, Action::JumpToPromptNext,
            Action::SearchOpen, Action::SearchClose,
            Action::SearchNext, Action::SearchPrev, Action::FontIncrease,
            Action::FontDecrease, Action::FontReset,
            Action::ResetTerminal,
            Action::ClearScreen, Action::ToggleFullscreen, Action::SelectAll,
            Action::CopyUrlToClipboard, Action::ToggleMouseReporting,
        ];
        for action in actions {
            let name = action.as_str();
            assert_eq!(
                parse_action(name),
                Some(action),
                "{action:?} canonical name {name:?} failed round-trip",
            );
        }
    }

    // ── madori_key_to_pty_bytes coverage ─────────────────────────
    //
    // The block below pins the byte translation that BOTH the
    // legacy single-pane (`main.rs`) and embedded-tear
    // (`gui_tear_attach.rs`) input paths now share. The named
    // `ctrl_r_produces_0x12_via_helper` test is the dedicated
    // regression guard for the 2026-05-26 Ctrl-R bug — the
    // embedded-tear path used to drop every Ctrl+letter on the
    // floor before reaching the PTY.

    fn mods(ctrl: bool, alt: bool, shift: bool, meta: bool) -> madori::event::Modifiers {
        madori::event::Modifiers { ctrl, alt, shift, meta }
    }

    #[test]
    fn ctrl_r_produces_0x12_via_helper() {
        // ─── REGRESSION GUARD ───────────────────────────────────
        // Pressing Ctrl-R in a mado window MUST produce the byte
        // 0x12 on the PTY so frostmourne's atuin/skim history
        // picker can fire. Before consolidation, the embedded-tear
        // path swallowed this keystroke. If this test fails, the
        // history picker is broken for every operator. Do not
        // weaken or delete it without an explicit replacement
        // assertion at the call site.
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(&key, &None, mods(true, false, false, false), false);
        assert_eq!(bytes.as_deref(), Some(&[0x12u8][..]),
            "Ctrl-R must produce 0x12 (DC2 / ^R) — frostmourne's history picker relies on it");
    }

    #[test]
    fn every_ctrl_letter_produces_correct_control_byte() {
        // The 26 Ctrl+letter sequences MUST translate to 0x01..0x1A.
        // Anything else regresses readline / atuin / vim / etc.
        for (idx, letter) in ('a'..='z').enumerate() {
            let expected = (idx as u8) + 1;
            let key = madori::event::KeyCode::Char(letter);
            let bytes = madori_key_to_pty_bytes(&key, &None, mods(true, false, false, false), false);
            assert_eq!(bytes.as_deref(), Some(&[expected][..]),
                "Ctrl-{} should map to {:#04x} (got {:?})", letter, expected, bytes);
        }
    }

    #[test]
    fn ctrl_letter_via_text_branch_also_works() {
        // Some keyboard layouts surface Ctrl+letter as `text = Some("r")`
        // instead of `KeyCode::Char('r')` with empty text. Both shapes
        // must produce the same control byte.
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(
            &key, &Some("r".to_string()), mods(true, false, false, false), false,
        );
        assert_eq!(bytes.as_deref(), Some(&[0x12u8][..]));
    }

    #[test]
    fn alt_char_prepends_escape() {
        let key = madori::event::KeyCode::Char('b');
        let bytes = madori_key_to_pty_bytes(&key, &None, mods(false, true, false, false), false);
        assert_eq!(bytes.as_deref(), Some(&[0x1b, b'b'][..]));
    }

    #[test]
    fn alt_text_prepends_escape() {
        let key = madori::event::KeyCode::Char('b');
        let bytes = madori_key_to_pty_bytes(
            &key, &Some("b".to_string()), mods(false, true, false, false), false,
        );
        assert_eq!(bytes.as_deref(), Some(&[0x1b, b'b'][..]));
    }

    #[test]
    fn bare_cmd_returns_none_so_caller_can_drop() {
        // Cmd-X with no matching keybinding is a GUI shortcut, not
        // PTY input. Helper returns None — caller drops.
        let key = madori::event::KeyCode::Char('x');
        let bytes = madori_key_to_pty_bytes(
            &key, &Some("x".to_string()), mods(false, false, false, true), false,
        );
        assert_eq!(bytes, None);
    }

    #[test]
    fn ctrl_cmd_letter_still_produces_control_byte() {
        // If both Ctrl and Cmd are held (e.g. global shortcut
        // intent that includes Ctrl), the helper still emits the
        // Ctrl byte; the keybinding lookup at the call site is
        // what decides whether to consume vs forward.
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(
            &key, &None, mods(true, false, false, true), false,
        );
        assert_eq!(bytes.as_deref(), Some(&[0x12u8][..]));
    }

    #[test]
    fn plain_text_passes_through() {
        let key = madori::event::KeyCode::Char('a');
        let bytes = madori_key_to_pty_bytes(
            &key, &Some("a".to_string()), mods(false, false, false, false), false,
        );
        assert_eq!(bytes.as_deref(), Some(&b"a"[..]));
    }

    #[test]
    fn shift_text_passes_through_uppercase() {
        // madori does OS-level composition so Shift+r arrives as text="R".
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(
            &key, &Some("R".to_string()), mods(false, false, true, false), false,
        );
        assert_eq!(bytes.as_deref(), Some(&b"R"[..]));
    }

    #[test]
    fn named_keys_map_to_canonical_bytes() {
        let m = mods(false, false, false, false);
        let cases: &[(madori::event::KeyCode, &[u8])] = &[
            (madori::event::KeyCode::Enter,     b"\r"),
            (madori::event::KeyCode::Backspace, b"\x7f"),
            (madori::event::KeyCode::Tab,       b"\t"),
            (madori::event::KeyCode::Escape,    b"\x1b"),
            (madori::event::KeyCode::Space,     b" "),
            (madori::event::KeyCode::Delete,    b"\x1b[3~"),
            (madori::event::KeyCode::PageUp,    b"\x1b[5~"),
            (madori::event::KeyCode::PageDown,  b"\x1b[6~"),
        ];
        for (key, expected) in cases {
            let bytes = madori_key_to_pty_bytes(key, &None, m, false);
            assert_eq!(bytes.as_deref(), Some(*expected),
                "named key {:?} should map to {:?}", key, expected);
        }
    }

    #[test]
    fn cursor_keys_normal_mode_emit_csi() {
        // DECCKM reset (default) → ESC [ <ch>
        let m = mods(false, false, false, false);
        for (key, ch) in [
            (madori::event::KeyCode::Up,    b'A'),
            (madori::event::KeyCode::Down,  b'B'),
            (madori::event::KeyCode::Right, b'C'),
            (madori::event::KeyCode::Left,  b'D'),
            (madori::event::KeyCode::Home,  b'H'),
            (madori::event::KeyCode::End,   b'F'),
        ] {
            let bytes = madori_key_to_pty_bytes(&key, &None, m, false);
            assert_eq!(bytes.as_deref(), Some(&[0x1b, b'[', ch][..]),
                "cursor key {:?} in normal mode should emit ESC [ {}", key, ch as char);
        }
    }

    #[test]
    fn cursor_keys_application_mode_emit_ss3() {
        // DECCKM set → ESC O <ch>
        let m = mods(false, false, false, false);
        for (key, ch) in [
            (madori::event::KeyCode::Up,    b'A'),
            (madori::event::KeyCode::Down,  b'B'),
            (madori::event::KeyCode::Right, b'C'),
            (madori::event::KeyCode::Left,  b'D'),
        ] {
            let bytes = madori_key_to_pty_bytes(&key, &None, m, true);
            assert_eq!(bytes.as_deref(), Some(&[0x1b, b'O', ch][..]),
                "cursor key {:?} in app mode should emit ESC O {}", key, ch as char);
        }
    }

    #[test]
    fn f_keys_map_to_xterm_sequences() {
        let m = mods(false, false, false, false);
        let cases: &[(u8, &[u8])] = &[
            (1,  b"\x1bOP"),     (2,  b"\x1bOQ"),     (3,  b"\x1bOR"),     (4,  b"\x1bOS"),
            (5,  b"\x1b[15~"),   (6,  b"\x1b[17~"),   (7,  b"\x1b[18~"),   (8,  b"\x1b[19~"),
            (9,  b"\x1b[20~"),   (10, b"\x1b[21~"),   (11, b"\x1b[23~"),   (12, b"\x1b[24~"),
        ];
        for (n, expected) in cases {
            let bytes = madori_key_to_pty_bytes(&madori::event::KeyCode::F(*n), &None, m, false);
            assert_eq!(bytes.as_deref(), Some(*expected),
                "F{} should map to {:?}", n, expected);
        }
    }

    #[test]
    fn unknown_key_with_no_text_returns_none() {
        // A keystroke that has no text and no name (e.g. media keys)
        // returns None so the call site can ignore it.
        let bytes = madori_key_to_pty_bytes(
            &madori::event::KeyCode::F(99),
            &None,
            mods(false, false, false, false),
            false,
        );
        // F(99) hits the F-key arm → f_key_escape returns an empty
        // Vec by design. Caller should treat empty-byte payload as
        // "ignore" semantically — that's preserved from the legacy
        // helper.
        assert_eq!(bytes.as_deref(), Some(&[][..]));
    }

    #[test]
    fn ctrl_non_letter_falls_through_to_text() {
        // Ctrl+] arrives as text="]" (or similar). The helper has no
        // ctrl-symbol mapping; it forwards the text as-is. That
        // preserves the legacy behaviour — terminal apps that want
        // ctrl-symbol handling read raw bytes via termios.
        let key = madori::event::KeyCode::Char(']');
        let bytes = madori_key_to_pty_bytes(
            &key, &Some("]".to_string()), mods(true, false, false, false), false,
        );
        assert_eq!(bytes.as_deref(), Some(&b"]"[..]));
    }

    // ── End-to-end regression: simulate the embedded-tear flow ──
    //
    // This test composes the keybind action lookup with the byte
    // helper exactly the way `gui_tear_attach.rs` does. It is the
    // canonical "the Ctrl-R bug cannot return" guard — if anyone
    // re-introduces a `meta || ctrl` drop guard in the tear path
    // without first calling `madori_key_to_pty_bytes`, this test
    // catches it at the unit level.

    #[test]
    fn embedded_tear_flow_ctrl_r_reaches_pty() {
        let manager = KeybindManager::with_mado_defaults();
        let event = madori::event::KeyEvent {
            key: madori::event::KeyCode::Char('r'),
            text: None,
            modifiers: mods(true, false, false, false),
            pressed: true,
        };

        // Step 1: keybind lookup. Ctrl-R has no default action —
        // so we MUST fall through to PTY translation.
        let action = manager.lookup_madori(&event);
        assert!(action.is_none(),
            "Ctrl-R must not have a default mado keybinding — \
             frostmourne owns it via skim+atuin");

        // Step 2: byte translation. Must produce 0x12 (^R / DC2).
        let bytes = madori_key_to_pty_bytes(
            &event.key, &event.text, event.modifiers, false,
        );
        assert_eq!(bytes.as_deref(), Some(&[0x12u8][..]),
            "Ctrl-R MUST be translated to 0x12 for frostmourne to receive it");
    }

    #[test]
    fn embedded_tear_flow_bare_cmd_drops() {
        // The symmetric case: Cmd+letter with no matching binding
        // returns None so the call site can drop (don't leak the
        // bare letter to the PTY).
        let manager = KeybindManager::with_mado_defaults();
        let event = madori::event::KeyEvent {
            key: madori::event::KeyCode::Char('j'),
            text: Some("j".to_string()),
            modifiers: mods(false, false, false, true),
            pressed: true,
        };

        let action = manager.lookup_madori(&event);
        assert!(action.is_none(), "Cmd+J has no default binding");

        let bytes = madori_key_to_pty_bytes(
            &event.key, &event.text, event.modifiers, false,
        );
        assert_eq!(bytes, None,
            "bare Cmd with no matching binding must NOT leak text to the PTY");
    }

    #[test]
    fn embedded_tear_flow_arrow_keys_respect_decckm() {
        // Vim, less, htop, btop, etc. set DECCKM (CSI ? 1 h) on
        // alt-screen entry and reset it on exit. The embedded-tear
        // path queries `pane_cursor_keys_mode` and passes the result
        // here; this test pins that arrow-key encoding flips
        // correctly with that input.
        let event = madori::event::KeyEvent {
            key: madori::event::KeyCode::Up,
            text: None,
            modifiers: mods(false, false, false, false),
            pressed: true,
        };

        // Normal mode (DECCKM reset, shell at the prompt) → ESC [ A.
        let normal = madori_key_to_pty_bytes(
            &event.key, &event.text, event.modifiers, false,
        );
        assert_eq!(normal.as_deref(), Some(&b"\x1b[A"[..]),
            "Up in normal mode must emit ESC [ A — bash prompt-history navigation depends on it");

        // Application mode (DECCKM set, vim in alt-screen) → ESC O A.
        let app = madori_key_to_pty_bytes(
            &event.key, &event.text, event.modifiers, true,
        );
        assert_eq!(app.as_deref(), Some(&b"\x1bOA"[..]),
            "Up in application mode must emit ESC O A — vim cursor-key handling depends on it");
    }

    #[test]
    fn embedded_tear_flow_common_shell_chords_all_reach_pty() {
        // Pin the full set of shell control chords that the embedded-
        // tear path must forward. If any one of these regresses to
        // None, the corresponding shell behaviour breaks.
        let cases: &[(char, u8, &str)] = &[
            ('a', 0x01, "Ctrl-A: beginning-of-line"),
            ('b', 0x02, "Ctrl-B: backward-char"),
            ('c', 0x03, "Ctrl-C: SIGINT"),
            ('d', 0x04, "Ctrl-D: EOF"),
            ('e', 0x05, "Ctrl-E: end-of-line"),
            ('f', 0x06, "Ctrl-F: forward-char"),
            ('k', 0x0b, "Ctrl-K: kill-line"),
            ('l', 0x0c, "Ctrl-L: clear-screen"),
            ('n', 0x0e, "Ctrl-N: next-history"),
            ('p', 0x10, "Ctrl-P: prev-history"),
            ('r', 0x12, "Ctrl-R: history-search-backward / atuin"),
            ('u', 0x15, "Ctrl-U: kill-line-backward"),
            ('w', 0x17, "Ctrl-W: kill-word-backward"),
            ('z', 0x1a, "Ctrl-Z: SIGTSTP"),
        ];
        for (ch, expected, label) in cases {
            let event = madori::event::KeyEvent {
                key: madori::event::KeyCode::Char(*ch),
                text: None,
                modifiers: mods(true, false, false, false),
                pressed: true,
            };
            let bytes = madori_key_to_pty_bytes(
                &event.key, &event.text, event.modifiers, false,
            );
            assert_eq!(bytes.as_deref(), Some(&[*expected][..]),
                "{} — Ctrl-{} must map to {:#04x}", label, ch, expected);
        }
    }
}
