//! Keybinding system — configurable key -> action mapping via awase.
//!
//! Uses `awase::Hotkey` and `awase::Binding` for key binding definitions,
//! providing a consistent hotkey representation across pleme-io apps.
//! Default keybindings use macOS-style Cmd as the primary modifier.

use pleme_kindstr_derive::KindStr;
use serde::{Deserialize, Serialize};

/// High-level terminal actions triggered by keybindings.
///
/// The config-name round-trip ([`Self::from_str_kind`] ↔
/// [`Self::as_str`]) is generated by `#[derive(KindStr)]` (the
/// macro-farm paired round-trip derive) from the per-variant
/// `#[kind(name = "...", alias = "...")]` attrs — one authored
/// action-name table instead of the hand-written `parse_action`
/// match. The canonical `name` is the serde snake_case spelling
/// (so `as_str` agrees with serde); the legacy / colon-form / verb-
/// order config spellings ride along as repeatable `alias`es.
/// The Phase-4-removed multiplexing spellings (`new_tab`,
/// `goto_split:next`, …) carry no `name`/`alias`, so `from_str_kind`
/// returns `None` for them — preserving `parse_action`'s "recognised
/// but no longer dispatched" behaviour.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
    KindStr,
    pleme_allvariants_derive::AllVariants,
)]
#[serde(rename_all = "snake_case")]
pub enum Action {
    #[kind(name = "copy")]
    Copy,
    #[kind(name = "paste")]
    Paste,
    #[kind(name = "paste_from_selection")]
    PasteFromSelection,
    #[kind(name = "scroll_up")]
    ScrollUp,
    #[kind(name = "scroll_down")]
    ScrollDown,
    #[kind(name = "scroll_page_up")]
    ScrollPageUp,
    #[kind(name = "scroll_page_down")]
    ScrollPageDown,
    #[kind(name = "scroll_to_top")]
    ScrollToTop,
    #[kind(name = "scroll_to_bottom")]
    ScrollToBottom,
    #[kind(name = "jump_to_prompt")]
    JumpToPrompt,
    #[kind(
        name = "jump_to_prompt_prev",
        alias = "jump_to_prompt:prev",
        alias = "jump_to_previous_prompt"
    )]
    JumpToPromptPrev,
    #[kind(
        name = "jump_to_prompt_next",
        alias = "jump_to_prompt:next",
        alias = "jump_to_next_prompt"
    )]
    JumpToPromptNext,
    #[kind(name = "search_open", alias = "search")]
    SearchOpen,
    #[kind(name = "search_close")]
    SearchClose,
    #[kind(name = "search_next")]
    SearchNext,
    #[kind(name = "search_prev")]
    SearchPrev,
    #[kind(name = "dir_picker_open", alias = "dir_picker", alias = "recent_dirs")]
    DirPickerOpen,
    #[kind(
        name = "session_picker_open",
        alias = "session_picker",
        alias = "session_switcher"
    )]
    SessionPickerOpen,
    /// Save the highlighted session-picker row's live session as a reusable
    /// preset (the keybind companion to the `save_session_as_preset` MCP
    /// verb). A no-op unless the picker is open with a live row highlighted.
    #[kind(name = "save_session_as_preset", alias = "save_preset")]
    SaveSessionAsPreset,
    /// **Reserved — consumed no-op for now.** Future home of the layout
    /// picker: the Ctrl-L analog of [`Action::SessionPickerOpen`]'s
    /// Ctrl-S, but switching *layouts* instead of sessions. Bound to
    /// `ctrl+l` in `default_bindings()` TODAY purely to **claim the
    /// chord and swallow it** so the keystroke no longer falls through
    /// to the PTY as `0x0c` (which the shell renders as clear-screen).
    /// The engine dispatch is an intentional consumed no-op until the
    /// layout picker lands — see `ux::engine`'s `LayoutPickerOpen` arm.
    #[kind(
        name = "layout_picker_open",
        alias = "layout_picker",
        alias = "layout_switcher"
    )]
    LayoutPickerOpen,
    #[kind(name = "font_increase", alias = "increase_font_size")]
    FontIncrease,
    #[kind(name = "font_decrease", alias = "decrease_font_size")]
    FontDecrease,
    #[kind(name = "font_reset", alias = "reset_font_size")]
    FontReset,
    // NewTab / CloseTab / NextTab / PrevTab / SplitHorizontal /
    // SplitVertical / FocusNext / FocusPrev / ClosePane removed
    // at Phase 4 — multiplexing lives in tear, not mado. See
    // theory/MADO-TEAR-M5.md. Users who want splits / tabs run
    // tear inside mado (or use `mado tear-attach --gpu`).
    #[kind(name = "reset_terminal", alias = "reset")]
    ResetTerminal,
    #[kind(name = "clear_screen")]
    ClearScreen,
    #[kind(name = "toggle_fullscreen")]
    ToggleFullscreen,
    #[kind(name = "select_all")]
    SelectAll,
    /// Select the PREVIOUS command's output (the OSC 133 `C` → next
    /// `A` zone) and copy it — one keystroke instead of dragging the
    /// mouse across a wrapped, scrolled-off region. Requires the shell
    /// integration scripts (`shell-integration/mado.*`) to be sourced,
    /// exactly like the prompt-jump actions above; without marks there
    /// is no zone and the action is a no-op.
    #[kind(
        name = "copy_last_command_output",
        alias = "copy_last_output",
        alias = "copy_command_output"
    )]
    CopyLastCommandOutput,
    #[kind(name = "copy_url_to_clipboard")]
    CopyUrlToClipboard,
    #[kind(name = "toggle_mouse_reporting")]
    ToggleMouseReporting,
}

/// A keybinding mapping an awase hotkey to a mado action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Keybinding {
    pub hotkey: awase::Hotkey,
    pub action: Action,
}

/// Keybinding manager with lookup.
pub struct KeybindManager {
    bindings: Vec<Keybinding>,
}

#[allow(dead_code)]
impl KeybindManager {
    /// Create with platform-appropriate default bindings.
    /// Construct an EMPTY KeybindManager — zero bindings, every
    /// keystroke falls through to the PTY by default. Operator
    /// principle: nothing is bound until explicitly opted in.
    ///
    /// For mado's curated baseline (Cmd-+/Cmd--/Cmd-0/Cmd-C/...)
    /// call [`KeybindManager::with_mado_defaults`] instead. That
    /// constructor IS the documented "default mado experience" —
    /// `new()` is for headless paths, tests, and operators who
    /// want to start from scratch.
    #[must_use]
    pub fn new() -> Self {
        Self {
            bindings: Vec::new(),
        }
    }

    /// Construct a KeybindManager pre-populated with mado's curated
    /// baseline (`default_bindings()`). This is what `main.rs` +
    /// `gui_tear_attach.rs` call so operators get a useful first-
    /// launch experience without writing a yaml file.
    ///
    /// Each binding can be removed via [`KeybindManager::unbind`]
    /// or replaced via [`KeybindManager::bind`]; the operator-
    /// visible set is `manager.bindings()`.
    #[must_use]
    pub fn with_mado_defaults() -> Self {
        Self {
            bindings: default_bindings(),
        }
    }

    /// Look up an action for the given awase hotkey.
    #[must_use]
    pub fn lookup(&self, hotkey: &awase::Hotkey) -> Option<Action> {
        self.bindings
            .iter()
            .find(|b| b.hotkey == *hotkey)
            .map(|b| b.action)
    }

    /// Look up an action using awase key + modifier components.
    #[must_use]
    pub fn lookup_key(&self, key: awase::Key, modifiers: awase::Modifiers) -> Option<Action> {
        let hotkey = awase::Hotkey::new(modifiers, key);
        self.lookup(&hotkey)
    }

    /// Add or replace a keybinding using an awase hotkey.
    pub fn bind(&mut self, hotkey: awase::Hotkey, action: Action) {
        self.bindings.retain(|b| b.hotkey != hotkey);
        self.bindings.push(Keybinding { hotkey, action });
    }

    /// Add or replace a keybinding parsed from a string (e.g., "cmd+c").
    pub fn bind_str(&mut self, hotkey_str: &str, action: Action) -> Result<(), awase::AwaseError> {
        let hotkey = awase::Hotkey::parse(hotkey_str)?;
        self.bind(hotkey, action);
        Ok(())
    }

    /// Remove a keybinding for the given hotkey.
    pub fn unbind(&mut self, hotkey: &awase::Hotkey) {
        self.bindings.retain(|b| b.hotkey != *hotkey);
    }

    /// All current bindings.
    #[must_use]
    pub fn bindings(&self) -> &[Keybinding] {
        &self.bindings
    }

    /// Convenience: look up an action directly from a madori
    /// KeyEvent. Encapsulates the modifier → awase + key → awase
    /// conversion so the tear-attach event loop (which doesn't
    /// pull main.rs's helpers) can dispatch keybindings the same
    /// way the local-PTY path does.
    ///
    /// Returns `None` when the key + modifiers don't match a
    /// bound action — caller falls back to forwarding the text
    /// to the PTY (or dropping it if a non-text modifier is held).
    #[must_use]
    pub fn lookup_madori(&self, event: &madori::event::KeyEvent) -> Option<Action> {
        let key = madori_key_to_awase(&event.key, &event.text)?;
        let mods = madori_modifiers_to_awase(event.modifiers);
        self.lookup(&awase::Hotkey::new(mods, key))
    }
}

/// Convert a madori::Modifiers to awase::Modifiers. Shared by
/// main.rs (local-PTY path) and gui_tear_attach.rs (tear path)
/// so both use the same modifier rules. `meta` (winit's term for
/// macOS Cmd) maps to `awase::Modifiers::CMD`.
#[must_use]
pub fn madori_modifiers_to_awase(m: madori::event::Modifiers) -> awase::Modifiers {
    let mut out = awase::Modifiers::NONE;
    if m.ctrl {
        out = out | awase::Modifiers::CTRL;
    }
    if m.alt {
        out = out | awase::Modifiers::ALT;
    }
    if m.shift {
        out = out | awase::Modifiers::SHIFT;
    }
    if m.meta {
        out = out | awase::Modifiers::CMD;
    }
    out
}

/// Convert a madori::KeyCode + optional text into an awase::Key.
/// Returns None for keys with no awase equivalent (e.g. unknown
/// scancode, multi-char text).
#[must_use]
pub fn madori_key_to_awase(
    key: &madori::event::KeyCode,
    text: &Option<String>,
) -> Option<awase::Key> {
    match key {
        madori::event::KeyCode::Enter => Some(awase::Key::Return),
        madori::event::KeyCode::Escape => Some(awase::Key::Escape),
        madori::event::KeyCode::Tab => Some(awase::Key::Tab),
        madori::event::KeyCode::Backspace => Some(awase::Key::Backspace),
        madori::event::KeyCode::Delete => Some(awase::Key::Delete),
        madori::event::KeyCode::Home => Some(awase::Key::Home),
        madori::event::KeyCode::End => Some(awase::Key::End),
        madori::event::KeyCode::PageUp => Some(awase::Key::PageUp),
        madori::event::KeyCode::PageDown => Some(awase::Key::PageDown),
        madori::event::KeyCode::Up => Some(awase::Key::Up),
        madori::event::KeyCode::Down => Some(awase::Key::Down),
        madori::event::KeyCode::Left => Some(awase::Key::Left),
        madori::event::KeyCode::Right => Some(awase::Key::Right),
        madori::event::KeyCode::F(n) => match n {
            1 => Some(awase::Key::F1),
            2 => Some(awase::Key::F2),
            3 => Some(awase::Key::F3),
            4 => Some(awase::Key::F4),
            5 => Some(awase::Key::F5),
            6 => Some(awase::Key::F6),
            7 => Some(awase::Key::F7),
            8 => Some(awase::Key::F8),
            9 => Some(awase::Key::F9),
            10 => Some(awase::Key::F10),
            11 => Some(awase::Key::F11),
            12 => Some(awase::Key::F12),
            _ => None,
        },
        madori::event::KeyCode::Char(ch) => char_to_awase_key(*ch),
        madori::event::KeyCode::Space => Some(awase::Key::Space),
        _ => {
            // Try to extract from text (e.g. shifted symbols).
            if let Some(t) = text {
                if let Some(ch) = t.chars().next() {
                    if t.len() == ch.len_utf8() {
                        return char_to_awase_key(ch);
                    }
                }
            }
            None
        }
    }
}

/// Lowercase-folded char → awase::Key. Centralizes the
/// printable-to-key map both event paths use.
#[must_use]
pub fn char_to_awase_key(ch: char) -> Option<awase::Key> {
    match ch.to_ascii_lowercase() {
        'a' => Some(awase::Key::A),
        'b' => Some(awase::Key::B),
        'c' => Some(awase::Key::C),
        'd' => Some(awase::Key::D),
        'e' => Some(awase::Key::E),
        'f' => Some(awase::Key::F),
        'g' => Some(awase::Key::G),
        'h' => Some(awase::Key::H),
        'i' => Some(awase::Key::I),
        'j' => Some(awase::Key::J),
        'k' => Some(awase::Key::K),
        'l' => Some(awase::Key::L),
        'm' => Some(awase::Key::M),
        'n' => Some(awase::Key::N),
        'o' => Some(awase::Key::O),
        'p' => Some(awase::Key::P),
        'q' => Some(awase::Key::Q),
        'r' => Some(awase::Key::R),
        's' => Some(awase::Key::S),
        't' => Some(awase::Key::T),
        'u' => Some(awase::Key::U),
        'v' => Some(awase::Key::V),
        'w' => Some(awase::Key::W),
        'x' => Some(awase::Key::X),
        'y' => Some(awase::Key::Y),
        'z' => Some(awase::Key::Z),
        '0' => Some(awase::Key::Num0),
        '1' => Some(awase::Key::Num1),
        '2' => Some(awase::Key::Num2),
        '3' => Some(awase::Key::Num3),
        '4' => Some(awase::Key::Num4),
        '5' => Some(awase::Key::Num5),
        '6' => Some(awase::Key::Num6),
        '7' => Some(awase::Key::Num7),
        '8' => Some(awase::Key::Num8),
        '9' => Some(awase::Key::Num9),
        ' ' => Some(awase::Key::Space),
        '/' => Some(awase::Key::Slash),
        '+' | '=' => Some(awase::Key::Equal),
        '-' => Some(awase::Key::Minus),
        ',' => Some(awase::Key::Comma),
        '.' => Some(awase::Key::Period),
        _ => None,
    }
}

impl Default for KeybindManager {
    fn default() -> Self {
        Self::new()
    }
}

/// Encode a cursor key under the active DECCKM mode.
///
/// `application_mode = true` → `ESC O <ch>` (DECCKM set, mode `?1h`).
/// `application_mode = false` → `ESC [ <ch>` (DECCKM reset, default).
///
/// `ch` is the trailing letter for the sequence:
/// `b'A'` Up, `b'B'` Down, `b'C'` Right, `b'D'` Left, `b'H'` Home,
/// `b'F'` End.
#[must_use]
pub fn cursor_key_bytes(ch: u8, application_mode: bool) -> Vec<u8> {
    if application_mode {
        vec![0x1b, b'O', ch]
    } else {
        vec![0x1b, b'[', ch]
    }
}

/// Encode an F1–F12 keystroke as the xterm-canonical escape sequence.
/// Returns an empty `Vec` for `n` outside `1..=12` to match the
/// legacy `main.rs` helper this consolidates.
#[must_use]
pub fn f_key_escape(n: u8) -> Vec<u8> {
    match n {
        1 => b"\x1bOP".to_vec(),
        2 => b"\x1bOQ".to_vec(),
        3 => b"\x1bOR".to_vec(),
        4 => b"\x1bOS".to_vec(),
        5 => b"\x1b[15~".to_vec(),
        6 => b"\x1b[17~".to_vec(),
        7 => b"\x1b[18~".to_vec(),
        8 => b"\x1b[19~".to_vec(),
        9 => b"\x1b[20~".to_vec(),
        10 => b"\x1b[21~".to_vec(),
        11 => b"\x1b[23~".to_vec(),
        12 => b"\x1b[24~".to_vec(),
        _ => vec![],
    }
}

/// Translate a madori `KeyEvent` (key + text + modifiers) into the
/// raw PTY byte sequence the running shell expects.
///
/// **Single source of truth** for the legacy `main.rs` path and the
/// embedded-tear `gui_tear_attach.rs` path. Prior to consolidation
/// these two paths had divergent logic — the tear path silently
/// dropped every `Ctrl+letter` keystroke (including `Ctrl-R`, which
/// killed atuin/skim history search). See the dedicated regression
/// test `ctrl_r_produces_0x12_via_helper` below — that one exists
/// to prevent the regression.
///
/// Returns:
/// - `Some(bytes)` when the keystroke maps to PTY bytes.
/// - `None` when the keystroke has no PTY translation — caller
///   decides whether to drop it (bare Cmd + no matching binding)
///   or ignore it (e.g. modifier-only keystroke).
///
/// `app_cursor_mode` is the active DECCKM state for the destination
/// terminal. Pass `false` for the embedded-tear path until tear-core
/// gains DECCKM tracking.
#[must_use]
pub fn madori_key_to_pty_bytes(
    key: &madori::event::KeyCode,
    text: &Option<String>,
    modifiers: madori::event::Modifiers,
    app_cursor_mode: bool,
) -> Option<Vec<u8>> {
    // Cmd-only (no Ctrl, no Alt) with no matching keybinding is a
    // GUI shortcut, not PTY input. Caller drops.
    if modifiers.meta && !modifiers.ctrl && !modifiers.alt {
        return None;
    }

    if let Some(t) = text {
        if !t.is_empty() {
            if modifiers.ctrl && t.len() == 1 {
                let ch = t.chars().next().unwrap();
                if ch.is_ascii_alphabetic() {
                    let ctrl_byte = (ch.to_ascii_lowercase() as u8) - b'a' + 1;
                    return Some(vec![ctrl_byte]);
                }
            }
            if modifiers.alt {
                let mut bytes = vec![0x1b];
                bytes.extend_from_slice(t.as_bytes());
                return Some(bytes);
            }
            return Some(t.as_bytes().to_vec());
        }
    }

    if modifiers.ctrl {
        if let madori::event::KeyCode::Char(ch) = key {
            if ch.is_ascii_alphabetic() {
                let ctrl_byte = (ch.to_ascii_lowercase() as u8) - b'a' + 1;
                return Some(vec![ctrl_byte]);
            }
        }
    }

    if modifiers.alt {
        if let madori::event::KeyCode::Char(ch) = key {
            let mut bytes = vec![0x1b];
            let mut buf = [0u8; 4];
            bytes.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());
            return Some(bytes);
        }
    }

    match key {
        madori::event::KeyCode::Enter => Some(b"\r".to_vec()),
        madori::event::KeyCode::Backspace => Some(b"\x7f".to_vec()),
        madori::event::KeyCode::Tab => Some(b"\t".to_vec()),
        madori::event::KeyCode::Escape => Some(b"\x1b".to_vec()),
        madori::event::KeyCode::Space => Some(b" ".to_vec()),
        madori::event::KeyCode::Up => Some(cursor_key_bytes(b'A', app_cursor_mode)),
        madori::event::KeyCode::Down => Some(cursor_key_bytes(b'B', app_cursor_mode)),
        madori::event::KeyCode::Right => Some(cursor_key_bytes(b'C', app_cursor_mode)),
        madori::event::KeyCode::Left => Some(cursor_key_bytes(b'D', app_cursor_mode)),
        madori::event::KeyCode::Home => Some(cursor_key_bytes(b'H', app_cursor_mode)),
        madori::event::KeyCode::End => Some(cursor_key_bytes(b'F', app_cursor_mode)),
        madori::event::KeyCode::Delete => Some(b"\x1b[3~".to_vec()),
        madori::event::KeyCode::PageUp => Some(b"\x1b[5~".to_vec()),
        madori::event::KeyCode::PageDown => Some(b"\x1b[6~".to_vec()),
        madori::event::KeyCode::F(n) => Some(f_key_escape(*n)),
        _ => None,
    }
}

/// Encode a key event for the Kitty keyboard protocol (CSI-u).
/// Returns the escape sequence bytes if the protocol is active,
/// `None` otherwise (caller falls back to the legacy translation).
///
/// **Single source of truth** for both event loops — the legacy
/// single-pane path (`main.rs`) and the embedded-tear path
/// (`gui_tear_attach.rs`). Callers gate on the destination
/// terminal's kitty mode stack (`Terminal::kitty_keyboard_flags`);
/// in tear mode that is mado's mirror Terminal, which tracks the
/// stack from the engate byte stream.
#[must_use]
pub fn kitty_encode_key(
    key: &madori::event::KeyCode,
    text: &Option<String>,
    modifiers: &madori::event::Modifiers,
    flags: u32,
) -> Option<Vec<u8>> {
    if flags == 0 {
        return None;
    }

    // Build modifier value: 1 + bitmask
    let mut mod_bits: u32 = 0;
    if modifiers.shift {
        mod_bits |= 1;
    }
    if modifiers.alt {
        mod_bits |= 2;
    }
    if modifiers.ctrl {
        mod_bits |= 4;
    }
    if modifiers.meta {
        mod_bits |= 8; // super
    }
    let mod_val = 1 + mod_bits;

    // Map key to unicode codepoint or special key number
    match key {
        madori::event::KeyCode::Enter => Some(kitty_key_seq(13, mod_val, b'u')),
        madori::event::KeyCode::Tab => Some(kitty_key_seq(9, mod_val, b'u')),
        madori::event::KeyCode::Backspace => Some(kitty_key_seq(127, mod_val, b'u')),
        madori::event::KeyCode::Escape => Some(kitty_key_seq(27, mod_val, b'u')),
        madori::event::KeyCode::Space => Some(kitty_key_seq(b' ' as u32, mod_val, b'u')),
        madori::event::KeyCode::Delete => Some(kitty_tilde_seq(3, mod_val)),
        madori::event::KeyCode::Up => Some(kitty_key_seq(1, mod_val, b'A')),
        madori::event::KeyCode::Down => Some(kitty_key_seq(1, mod_val, b'B')),
        madori::event::KeyCode::Right => Some(kitty_key_seq(1, mod_val, b'C')),
        madori::event::KeyCode::Left => Some(kitty_key_seq(1, mod_val, b'D')),
        madori::event::KeyCode::Home => Some(kitty_key_seq(1, mod_val, b'H')),
        madori::event::KeyCode::End => Some(kitty_key_seq(1, mod_val, b'F')),
        madori::event::KeyCode::PageUp => Some(kitty_tilde_seq(5, mod_val)),
        madori::event::KeyCode::PageDown => Some(kitty_tilde_seq(6, mod_val)),
        madori::event::KeyCode::F(n) => {
            let (num, suffix) = match n {
                1 => (1, b'P'),
                2 => (1, b'Q'),
                3 => (1, b'R'),
                4 => (1, b'S'),
                5 => (15, b'~'),
                6 => (17, b'~'),
                7 => (18, b'~'),
                8 => (19, b'~'),
                9 => (20, b'~'),
                10 => (21, b'~'),
                11 => (23, b'~'),
                12 => (24, b'~'),
                _ => return None,
            };
            if suffix == b'~' {
                Some(kitty_tilde_seq(num, mod_val))
            } else {
                Some(kitty_key_seq(num, mod_val, suffix))
            }
        }
        madori::event::KeyCode::Char(ch) => {
            // Level 1 (disambiguate): only encode with modifiers beyond shift
            if mod_bits <= 1 {
                // No modifiers or just shift — send as normal UTF-8
                return None;
            }
            let cp = *ch as u32;
            Some(kitty_key_seq(cp, mod_val, b'u'))
        }
        _ => {
            // Try text content
            if let Some(t) = text {
                if let Some(ch) = t.chars().next() {
                    if t.len() == ch.len_utf8() && mod_bits > 1 {
                        return Some(kitty_key_seq(ch as u32, mod_val, b'u'));
                    }
                }
            }
            None
        }
    }
}

/// Build `CSI number ; modifiers X` for the Kitty protocol. Digits go
/// through the shared byte-wise emitter (★★ TYPED EMISSION — no
/// `format!()` of escape bytes).
fn kitty_key_seq(number: u32, modifiers: u32, suffix: u8) -> Vec<u8> {
    let mut out = Vec::with_capacity(16);
    out.extend_from_slice(b"\x1b[");
    if modifiers <= 1 && suffix != b'u' {
        // Arrow/Home/End without modifiers — standard CSI X
        out.push(suffix);
        return out;
    }
    crate::ux::mouse_report::push_decimal(&mut out, number as usize);
    if modifiers > 1 {
        out.push(b';');
        crate::ux::mouse_report::push_decimal(&mut out, modifiers as usize);
    }
    out.push(suffix);
    out
}

/// Build `CSI number ; modifiers ~` for the Kitty protocol (tilde
/// keys). Unlike [`kitty_key_seq`], the key number is always emitted —
/// `ESC [ 5 ~` is the unmodified form, never a bare `ESC [ ~`.
fn kitty_tilde_seq(number: u32, modifiers: u32) -> Vec<u8> {
    let mut out = Vec::with_capacity(16);
    out.extend_from_slice(b"\x1b[");
    crate::ux::mouse_report::push_decimal(&mut out, number as usize);
    if modifiers > 1 {
        out.push(b';');
        crate::ux::mouse_report::push_decimal(&mut out, modifiers as usize);
    }
    out.push(b'~');
    out
}

/// Parse an action name from config into an [`Action`]. Thin wrapper
/// over the derived [`Action::from_str_kind`] — the canonical names +
/// aliases live on the per-variant `#[kind(...)]` attrs. The
/// Phase-4-removed multiplexing spellings (`new_tab`, `close_tab`,
/// `split_horizontal`, `goto_split:next`, `close_surface`, …) carry no
/// `#[kind]` entry, so they fall through to `None` exactly as before —
/// "recognised in legacy configs but no longer dispatched."
pub fn parse_action(name: &str) -> Option<Action> {
    Action::from_str_kind(name)
}

/// Construct the keybind manager exactly as the GUI assembles it for
/// the default (embedded-tear) window: mado's curated baseline
/// (`with_mado_defaults`) plus the operator's `keybinds.custom`
/// entries from config. Shared by the GUI-side kanshou
/// `simulate_chord` resolver and the MCP-side no-GUI fallback so
/// chord→Action resolution can't drift between the two surfaces.
/// Unparseable triggers / unknown actions warn-and-skip, matching
/// the tolerant load behaviour of the main.rs config path.
#[must_use]
pub fn manager_from_config(config: &crate::config::MadoConfig) -> KeybindManager {
    let mut mgr = KeybindManager::with_mado_defaults();
    for entry in &config.keybinds.custom {
        if let Some(action) = parse_action(&entry.action) {
            if let Err(e) = mgr.bind_str(&entry.trigger, action) {
                tracing::warn!(trigger = %entry.trigger, error = %e, "failed to parse custom keybind trigger");
            }
        } else {
            tracing::warn!(action = %entry.action, "unknown keybind action");
        }
    }
    mgr
}

/// Helper to create a binding from an awase hotkey.
fn hk(modifiers: awase::Modifiers, key: awase::Key) -> awase::Hotkey {
    awase::Hotkey::new(modifiers, key)
}

/// Default keybindings (macOS-style: Cmd as primary modifier).
fn default_bindings() -> Vec<Keybinding> {
    use awase::Key;
    use awase::Modifiers;
    use awase::atlas_chord;

    // Atlas-resolved chords — every cross-GUI-terminal binding pulls
    // its chord from `ishou_tokens::FleetKeybinds::prescribed()` via
    // `awase::atlas_chord!`. The macro stringifies the field name as
    // the panic label so an atlas drift names the offending intent
    // automatically. Guard convergence test in `tests::mado_default
    // _bindings_converge_with_fleet_atlas` pins the mapping.
    let kb = ishou_tokens::FleetKeybinds::prescribed();

    // App-specific chords NOT in the atlas (mado-only ergonomics +
    // OSC-133 prompt navigation + scroll keys). These stay
    // hand-wired until the atlas earns a third consumer for each.
    let cmd = Modifiers::CMD;
    let cmd_shift = Modifiers::CMD | Modifiers::SHIFT;
    let ctrl = Modifiers::CTRL;
    let none = Modifiers::NONE;

    vec![
        // Clipboard — atlas-sourced.
        Keybinding {
            hotkey: atlas_chord!(kb.copy),
            action: Action::Copy,
        },
        Keybinding {
            hotkey: atlas_chord!(kb.paste),
            action: Action::Paste,
        },
        // Search — atlas-sourced.
        Keybinding {
            hotkey: atlas_chord!(kb.search_open),
            action: Action::SearchOpen,
        },
        Keybinding {
            hotkey: atlas_chord!(kb.search_close),
            action: Action::SearchClose,
        },
        Keybinding {
            hotkey: atlas_chord!(kb.search_next),
            action: Action::SearchNext,
        },
        Keybinding {
            hotkey: atlas_chord!(kb.search_prev),
            action: Action::SearchPrev,
        },
        // Font — atlas-sourced.
        Keybinding {
            hotkey: atlas_chord!(kb.font_increase),
            action: Action::FontIncrease,
        },
        Keybinding {
            hotkey: atlas_chord!(kb.font_decrease),
            action: Action::FontDecrease,
        },
        Keybinding {
            hotkey: atlas_chord!(kb.font_reset),
            action: Action::FontReset,
        },
        // Fullscreen — atlas-sourced.
        Keybinding {
            hotkey: atlas_chord!(kb.toggle_fullscreen),
            action: Action::ToggleFullscreen,
        },
        // Scroll — mado-specific (no atlas intent yet).
        Keybinding {
            hotkey: hk(none, Key::PageUp),
            action: Action::ScrollPageUp,
        },
        Keybinding {
            hotkey: hk(none, Key::PageDown),
            action: Action::ScrollPageDown,
        },
        Keybinding {
            hotkey: hk(cmd, Key::Home),
            action: Action::ScrollToTop,
        },
        Keybinding {
            hotkey: hk(cmd, Key::End),
            action: Action::ScrollToBottom,
        },
        // Prompt navigation — ghostty-canonical Cmd+Up / Cmd+Down on
        // OSC 133 prompt marks. Requires the shell integration scripts
        // (see shell-integration/mado.*) to be sourced. mado-specific.
        Keybinding {
            hotkey: hk(cmd, Key::Up),
            action: Action::JumpToPromptPrev,
        },
        Keybinding {
            hotkey: hk(cmd, Key::Down),
            action: Action::JumpToPromptNext,
        },
        // Directory frecency overlay (轍 wadachi) — Cmd+G ("go to dir").
        // mado-specific (no atlas intent yet); reader-only picker.
        Keybinding {
            hotkey: hk(cmd, Key::G),
            action: Action::DirPickerOpen,
        },
        // Praça session picker — Ctrl-S ("switch session"): fuzzy-browse
        // + switch the frecency-ranked sessions praça tracks. The rare
        // fallback to auto-attach-on-cd (PRACA.md M0). mado-specific
        // (no atlas intent yet). Drives the SAME switch channel as
        // auto-attach + the `switch_session` MCP tool.
        Keybinding {
            hotkey: hk(ctrl, Key::S),
            action: Action::SessionPickerOpen,
        },
        // ★ Ctrl+SHIFT+S lands here too, and that is a SAFETY binding, not a
        // convenience.
        //
        // Unbound, this chord fell through to `madori_key_to_pty_bytes`, which
        // sees `text = Some("S")` with ctrl held and emits `0x13` — XOFF. mado
        // never touches termios, so the PTY carries macOS's default `ixon` with
        // `stop = ^S` (verified 2026-08-21 by reading `stty -a` inside a live
        // mado PTY), and 0x13 stops all output from that shell until someone
        // sends Ctrl-Q. The terminal looks hung, which is indistinguishable
        // from "Ctrl-S is broken" — and the recovery is worse than the bug:
        // with the PTY stopped, a write to the master blocks, so the MCP
        // `send_keys` path cannot deliver the Ctrl-Q that would unstick it
        // (measured: a 120 s timeout with the session still frozen).
        //
        // Binding it closes the trap at the only layer that can: the chord now
        // resolves to an action, and `on_key` returns Consumed before the PTY
        // translation is ever reached. Note mado has ALREADY taken bare Ctrl-S
        // for this picker, so the operator has no intentional XOFF gesture left
        // to preserve — this removes accident surface, not a feature.
        //
        // Deliberately NOT fixed by clearing IXON on the PTY: that would change
        // flow-control semantics for every program running inside mado, which is
        // a far larger decision than closing one chord.
        Keybinding {
            hotkey: hk(ctrl | Modifiers::SHIFT, Key::S),
            action: Action::SessionPickerOpen,
        },
        // Save the highlighted live session-picker row as a preset —
        // Cmd+Shift+S ("save"). The keybind companion to the
        // `save_session_as_preset` MCP verb; a no-op unless Ctrl-S is open
        // with a live row highlighted. mado-specific.
        Keybinding {
            hotkey: hk(cmd_shift, Key::S),
            action: Action::SaveSessionAsPreset,
        },
        // Layout picker — Ctrl-L ("switch layout"): RESERVED. The
        // layout analog of Ctrl-S (sessions). Bound today as a consumed
        // no-op (see Action::LayoutPickerOpen + its engine arm) so
        // Ctrl-L stops falling through to the shell as 0x0c
        // (clear-screen); the picker itself lands later. mado-specific.
        Keybinding {
            hotkey: hk(ctrl, Key::L),
            action: Action::LayoutPickerOpen,
        },
        // Copy the previous command's output — Cmd+Shift+C, the
        // deliberate sibling of Cmd+C (copy the selection). Chosen
        // because it is the one free chord next to the copy the
        // operator already knows: the atlas claims D-c / D-v / D-a /
        // D-f / D-g / D-S-g / D-= / D-- / D-0 / D-C-f / D-k, and
        // mado's own map claims Cmd+Up/Down/Home/End, Cmd+G, Ctrl-S,
        // Ctrl-L, Cmd+Shift+S and Cmd+Shift+R — Cmd+Shift+C is
        // untaken in both. mado-specific (no atlas intent yet).
        Keybinding {
            hotkey: hk(cmd_shift, Key::C),
            action: Action::CopyLastCommandOutput,
        },
        // Terminal — mado-specific (no atlas reset intent).
        Keybinding {
            hotkey: hk(cmd_shift, Key::R),
            action: Action::ResetTerminal,
        },
        // ── Linux clipboard ergonomics ───────────────────────────────
        // The atlas resolves `kb.copy` / `kb.paste` to `D-c` / `D-v`
        // (Cmd) fleet-wide. On Linux `Cmd` maps to Super (the Windows
        // key), which is not what Linux terminal operators reach for
        // — `Ctrl+C` is claimed by SIGINT, so the terminal convention
        // is `Ctrl+Shift+C` / `Ctrl+Shift+V`. Neither chord is claimed
        // anywhere else in this map or in the atlas (the atlas claims
        // D-C-f but no Ctrl+Shift+letter), so these are additive: mac
        // operators keep Cmd+C / Cmd+V unchanged, Linux operators gain
        // the shortcut they expect. Reported 2026-08-17 on ggg:
        // "não funciona colar".
        //
        // Scope: `cfg!(target_os = "linux")` — a Windows report would
        // extend this to `not(target_os = "macos")`, mirroring the
        // `default_decorations()` split.
        #[cfg(target_os = "linux")]
        Keybinding {
            hotkey: hk(Modifiers::CTRL | Modifiers::SHIFT, Key::C),
            action: Action::Copy,
        },
        #[cfg(target_os = "linux")]
        Keybinding {
            hotkey: hk(Modifiers::CTRL | Modifiers::SHIFT, Key::V),
            action: Action::Paste,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_is_empty() {
        // Operator principle: zero bindings until explicitly opted in.
        let mgr = KeybindManager::new();
        assert!(mgr.bindings().is_empty());
    }

    // ── Cross-platform clipboard regression seal ─────────────────────
    //
    // Two rules, one per platform, both provable at compile+test time.
    // If either regresses, the failure names the exact broken chord
    // rather than surfacing as "colar não funciona" in a chat log.

    #[cfg(target_os = "macos")]
    #[test]
    fn macos_clipboard_uses_cmd_c_and_cmd_v() {
        // The macOS operator must keep the atlas-canonical Cmd+C /
        // Cmd+V; any Linux-facing change that displaces them regresses
        // here first, not in a review comment on a merged PR.
        let mgr = KeybindManager::with_mado_defaults();
        let cmd = awase::Modifiers::CMD;
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::C)),
            Some(Action::Copy),
            "macOS lost Cmd+C = Copy"
        );
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::V)),
            Some(Action::Paste),
            "macOS lost Cmd+V = Paste"
        );
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn linux_clipboard_carries_ctrl_shift_c_and_ctrl_shift_v_extras() {
        // Linux gains Ctrl+Shift+C / Ctrl+Shift+V as additive bindings
        // (Ctrl+C is claimed by SIGINT). The atlas defaults are still
        // registered — Ctrl+Shift+C/V is a superset, not a
        // replacement — so a Linux operator can use whichever chord
        // they know.
        let mgr = KeybindManager::with_mado_defaults();
        let cs = awase::Modifiers::CTRL | awase::Modifiers::SHIFT;
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cs, awase::Key::C)),
            Some(Action::Copy),
            "Linux lost Ctrl+Shift+C = Copy"
        );
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cs, awase::Key::V)),
            Some(Action::Paste),
            "Linux lost Ctrl+Shift+V = Paste"
        );
    }

    #[test]
    fn with_mado_defaults_populates_baseline() {
        let mgr = KeybindManager::with_mado_defaults();
        assert!(!mgr.bindings().is_empty());
        // Sanity-check the canonical font-zoom triplet is present.
        let cmd = awase::Modifiers::CMD;
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::Equal)),
            Some(Action::FontIncrease)
        );
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::Minus)),
            Some(Action::FontDecrease)
        );
        assert_eq!(
            mgr.lookup(&awase::Hotkey::new(cmd, awase::Key::Num0)),
            Some(Action::FontReset)
        );
    }

    #[test]
    fn mado_default_bindings_converge_with_fleet_atlas() {
        // The 10 atlas-sourced chords in `default_bindings()` must
        // round-trip through `awase::Hotkey::parse_atlas_chord` and
        // match the chord declared in `ishou_tokens::FleetKeybinds::
        // prescribed()`. Drift in either layer (atlas changes a
        // chord, or mado's default_bindings starts hand-coding again)
        // fails this Guard chain loudly rather than at operator-press
        // time.
        let mgr = KeybindManager::with_mado_defaults();
        let kb = ishou_tokens::FleetKeybinds::prescribed();

        // For each (intent, expected action), the binding manager
        // must return that action when looked up with the
        // atlas-parsed hotkey.
        let atlas_actions: &[(&str, Action)] = &[
            (kb.copy, Action::Copy),
            (kb.paste, Action::Paste),
            (kb.search_open, Action::SearchOpen),
            (kb.search_close, Action::SearchClose),
            (kb.search_next, Action::SearchNext),
            (kb.search_prev, Action::SearchPrev),
            (kb.font_increase, Action::FontIncrease),
            (kb.font_decrease, Action::FontDecrease),
            (kb.font_reset, Action::FontReset),
            (kb.toggle_fullscreen, Action::ToggleFullscreen),
        ];
        for (chord, expected) in atlas_actions {
            let hk = awase::Hotkey::parse_atlas_chord(chord)
                .unwrap_or_else(|e| panic!("atlas chord {chord:?} parse failed: {e}"));
            assert_eq!(
                mgr.lookup(&hk),
                Some(*expected),
                "mado default for atlas chord {chord:?} does not bind {expected:?}",
            );
        }

        // Symmetric Guard assertion via ishou's typed convergence
        // helper. Catches the same drift class but with the named-
        // intent error message ("font_increase chord drift") rather
        // than the action-lookup mismatch above.
        ishou_tokens::convergence::Guard::for_app("mado")
            .expect_copy(kb.copy)
            .expect_paste(kb.paste)
            .expect_search_open(kb.search_open)
            .expect_search_close(kb.search_close)
            .expect_search_next(kb.search_next)
            .expect_search_prev(kb.search_prev)
            .expect_font_increase(kb.font_increase)
            .expect_font_decrease(kb.font_decrease)
            .expect_font_reset(kb.font_reset)
            .expect_toggle_fullscreen(kb.toggle_fullscreen)
            .run();
    }

    #[test]
    fn lookup_copy() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::C);
        assert_eq!(mgr.lookup(&hk), Some(Action::Copy));
    }

    #[test]
    fn lookup_paste() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::V);
        assert_eq!(mgr.lookup(&hk), Some(Action::Paste));
    }

    #[test]
    fn lookup_no_match() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::X);
        assert_eq!(mgr.lookup(&hk), None);
    }

    #[test]
    fn custom_binding() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CTRL, awase::Key::R);
        mgr.bind(hk, Action::ResetTerminal);
        assert_eq!(mgr.lookup(&hk), Some(Action::ResetTerminal));
    }

    #[test]
    fn unbind() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::C);
        assert!(mgr.lookup(&hk).is_some());
        mgr.unbind(&hk);
        assert!(mgr.lookup(&hk).is_none());
    }

    #[test]
    fn rebind_replaces() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::C);
        mgr.bind(hk, Action::ResetTerminal);
        assert_eq!(mgr.lookup(&hk), Some(Action::ResetTerminal));
    }

    #[test]
    fn lookup_key_works() {
        let mgr = KeybindManager::with_mado_defaults();
        let action = mgr.lookup_key(awase::Key::C, awase::Modifiers::CMD);
        assert_eq!(action, Some(Action::Copy));
    }

    #[test]
    fn search_bindings() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk_open = awase::Hotkey::new(awase::Modifiers::CMD, awase::Key::F);
        assert_eq!(mgr.lookup(&hk_open), Some(Action::SearchOpen));

        let hk_close = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::Escape);
        assert_eq!(mgr.lookup(&hk_close), Some(Action::SearchClose));
    }

    #[test]
    fn bind_str_valid() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let result = mgr.bind_str("cmd+t", Action::Copy);
        assert!(result.is_ok());
        let hk = awase::Hotkey::parse("cmd+t").unwrap();
        assert_eq!(mgr.lookup(&hk), Some(Action::Copy));
    }

    #[test]
    fn bind_str_invalid() {
        let mut mgr = KeybindManager::with_mado_defaults();
        let result = mgr.bind_str("not_a_real_hotkey!!!", Action::Copy);
        assert!(result.is_err());
    }

    #[test]
    fn default_bindings_count() {
        let mgr = KeybindManager::with_mado_defaults();
        // Default bindings after Phase 4 (multiplexing actions
        // removed): clipboard (2) + search (4) + font (3) +
        // scroll (4) + prompt jump (2) + terminal (1) + fullscreen
        // (1) + dir-picker (1) + session-picker (1) + layout-picker
        // (1, reserved no-op) + save-as-preset (1) +
        // copy-last-command-output (1) = 22.
        //
        // Linux adds Ctrl+Shift+C / Ctrl+Shift+V as additive
        // clipboard bindings (Ctrl+C is claimed by SIGINT), so the
        // linux count is 24 before the XOFF seal below. See `linux_clipboard_carries_
        // ctrl_shift_c_and_ctrl_shift_v_extras` for the seal.
        // +1 (23 / 25 on linux) for the ctrl+SHIFT+s XOFF seal — see
        // `ctrl_shift_s_is_bound_so_it_can_never_reach_the_pty_as_xoff`.
        // That binding exists to stop an unbound chord falling through to
        // the PTY as 0x13 and freezing the terminal, so if this count ever
        // drops back by one, read that test before "fixing" the number.
        #[cfg(target_os = "linux")]
        let expected = 25;
        #[cfg(not(target_os = "linux"))]
        let expected = 23;
        assert_eq!(mgr.bindings().len(), expected);
    }

    #[test]
    fn all_actions_serializable() {
        // `Action::ALL` is DERIVED by `#[derive(AllVariants)]`, so this is
        // exhaustive by construction — a new variant joins it with no edit
        // here. It replaced a hand-listed array that had already drifted to
        // 28 of 29 (missing `SaveSessionAsPreset`).
        assert!(
            !Action::ALL.is_empty(),
            "the derived catalog must not be empty"
        );
        for action in Action::ALL {
            let json = serde_json::to_string(action);
            assert!(json.is_ok(), "Failed to serialize {:?}", action);
            let json_str = json.unwrap();
            let parsed: Result<Action, _> = serde_json::from_str(&json_str);
            assert!(parsed.is_ok(), "Failed to deserialize {:?}", action);
            assert_eq!(*action, parsed.unwrap());
        }
    }

    /// `Action::ALL` is generated by `#[derive(AllVariants)]`; this pins that
    /// it still is.
    ///
    /// History, because the correction matters more than the fix: the
    /// serialization test above used to be a HAND-LISTED array whose name
    /// promised what its body could not keep, and it had already drifted to
    /// 28 of 29 (missing `SaveSessionAsPreset`). The first repair was this
    /// source scan, written alongside a claim that a derived `ALL` was
    /// DESIGN and needed a change to `tatara-rust-derive::KindRoundTripSpec`.
    ///
    /// **That claim was wrong.** `pleme-allvariants-derive` already exists,
    /// mado already depended on it, and `fibers.rs` already stacks it with
    /// `KindStr` on one enum — the exact idiom. So the destination was
    /// reachable in a single derive line the whole time, and the doctrine
    /// docs that repeated the DESIGN claim were corrected with this commit.
    /// The lesson is the fleet's own: ground a claim about how two existing
    /// primitives relate by reading them, not by inferring from one of them.
    ///
    /// What survives is narrow and worth keeping — a check that the derive
    /// is still doing the generating, so nobody replaces it with a hand-kept
    /// const and reopens the drift. Tier: **CI-caught**; the exhaustiveness
    /// itself is now the derive's job, not this test's.
    #[test]
    fn the_all_actions_test_actually_lists_every_action() {
        let src = include_str!("keybind.rs");

        let enum_body = src
            .split_once("pub enum Action {")
            .expect("Action enum must exist")
            .1
            .split_once("\n}")
            .expect("Action enum must terminate")
            .0;
        let declared: Vec<&str> = enum_body
            .lines()
            .map(str::trim)
            .filter(|l| {
                !l.is_empty()
                    && !l.starts_with("//")
                    && !l.starts_with('#')
                    && l.ends_with(',')
                    && l.chars().next().is_some_and(char::is_uppercase)
            })
            .map(|l| l.trim_end_matches(','))
            .collect();
        assert!(
            declared.len() > 20,
            "parser found only {} variants — it has broken, and a broken \
             parser here reports FALSE SAFETY: fix the parser, do not \
             weaken the assert",
            declared.len()
        );

        assert_eq!(
            Action::ALL.len(),
            declared.len(),
            "`Action::ALL` has {} entries but {} variants are declared. \
             AllVariants generates ALL, so a mismatch means the derive was \
             removed and ALL hand-rolled — put the derive back rather than \
             maintaining the list.",
            Action::ALL.len(),
            declared.len()
        );
    }

    #[test]
    fn test_scroll_page_up_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::PageUp);
        assert_eq!(mgr.lookup(&hk), Some(Action::ScrollPageUp));
    }

    #[test]
    fn test_scroll_page_down_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::NONE, awase::Key::PageDown);
        assert_eq!(mgr.lookup(&hk), Some(Action::ScrollPageDown));
    }

    // test_focus_next_binding / test_focus_prev_binding /
    // test_close_pane_binding removed at Phase 4 — the actions
    // they exercised no longer exist; mado is single-pane now.

    #[test]
    fn test_toggle_fullscreen_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::CTRL,
            awase::Key::F,
        );
        assert_eq!(mgr.lookup(&hk), Some(Action::ToggleFullscreen));
    }

    #[test]
    fn test_reset_terminal_binding() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::SHIFT,
            awase::Key::R,
        );
        assert_eq!(mgr.lookup(&hk), Some(Action::ResetTerminal));
    }

    #[test]
    fn test_total_default_bindings_count() {
        let mgr = KeybindManager::with_mado_defaults();
        // Cross-platform: 22 chords, +2 for the linux clipboard
        // extras (Ctrl+Shift+C/V). See `default_bindings_count` for
        // the itemization.
        // +1 (23 / 25 on linux) for the ctrl+SHIFT+s XOFF seal — see
        // `ctrl_shift_s_is_bound_so_it_can_never_reach_the_pty_as_xoff`.
        // That binding exists to stop an unbound chord falling through to
        // the PTY as 0x13 and freezing the terminal, so if this count ever
        // drops back by one, read that test before "fixing" the number.
        #[cfg(target_os = "linux")]
        let expected = 25;
        #[cfg(not(target_os = "linux"))]
        let expected = 23;
        assert_eq!(mgr.bindings().len(), expected);
    }

    #[test]
    fn copy_last_command_output_bound_to_cmd_shift_c() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::SHIFT,
            awase::Key::C,
        );
        assert_eq!(mgr.lookup(&hk), Some(Action::CopyLastCommandOutput));
    }

    /// The chord must not shadow — or be shadowed by — anything
    /// already in the default map. `lookup` is first-match-wins over a
    /// `Vec`, so a duplicate hotkey silently disables whichever entry
    /// lands later; this pins that Cmd+Shift+C is claimed exactly once.
    #[test]
    fn copy_last_command_output_chord_is_claimed_exactly_once() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::SHIFT,
            awase::Key::C,
        );
        let claimants: Vec<Action> = mgr
            .bindings()
            .iter()
            .filter(|b| b.hotkey == hk)
            .map(|b| b.action)
            .collect();
        assert_eq!(
            claimants,
            vec![Action::CopyLastCommandOutput],
            "Cmd+Shift+C must be bound once, and to this action",
        );
    }

    #[test]
    fn copy_last_command_output_action_name_round_trips() {
        assert_eq!(
            parse_action("copy_last_command_output"),
            Some(Action::CopyLastCommandOutput)
        );
        assert_eq!(
            parse_action("copy_last_output"),
            Some(Action::CopyLastCommandOutput)
        );
        assert_eq!(
            parse_action("copy_command_output"),
            Some(Action::CopyLastCommandOutput)
        );
    }

    #[test]
    fn session_picker_bound_to_ctrl_s() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CTRL, awase::Key::S);
        assert_eq!(mgr.lookup(&hk), Some(Action::SessionPickerOpen));
    }

    #[test]
    fn ctrl_shift_s_is_bound_so_it_can_never_reach_the_pty_as_xoff() {
        // ★ THE XOFF TRAP (2026-08-21).
        //
        // Two independently-verified facts meet here:
        //
        //  1. A live mado PTY carries macOS's default termios — `stty -a`
        //     inside one reports `ixon` (ON) with `stop = ^S`. mado never
        //     calls tcsetattr, so byte 0x13 written to that PTY stops all
        //     output from the shell until a Ctrl-Q arrives. Proved by writing
        //     0x13 to a live session mid-stream: output halted and stayed
        //     halted.
        //  2. `madori_key_to_pty_bytes` turns Ctrl + an ASCII letter into that
        //     byte from `text`, and macOS reports Ctrl+SHIFT+S with
        //     `text = Some("S")` — uppercase, still ascii_alphabetic, still
        //     folded to 's'. So the shift variant produced 0x13.
        //
        // Unbound, that chord fell straight through the action dispatch into
        // the PTY translation and froze the terminal — indistinguishable from
        // "Ctrl-S is broken", and unrecoverable through the MCP surface,
        // because a write to a stopped PTY master blocks (measured: 120 s
        // timeout, session still frozen).
        //
        // The binding is the seal: a resolved action returns Consumed from
        // `on_key` before the PTY translation is reached. This asserts the
        // seal, and then asserts the trap it closes is real — so if someone
        // removes the binding as redundant, this fails and says why.
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CTRL | awase::Modifiers::SHIFT,
            awase::Key::S,
        );
        assert_eq!(
            mgr.lookup(&hk),
            Some(Action::SessionPickerOpen),
            "ctrl+shift+s must resolve to an action; unbound it emits XOFF"
        );

        // The trap, demonstrated: this is what an unbound ctrl+shift+s would
        // have sent. 0x13 is XOFF.
        let bytes = madori_key_to_pty_bytes(
            &madori::event::KeyCode::Char('S'),
            &Some("S".to_string()),
            madori::event::Modifiers {
                ctrl: true,
                shift: true,
                alt: false,
                meta: false,
            },
            false,
        );
        assert_eq!(
            bytes,
            Some(vec![0x13]),
            "if this no longer produces XOFF the hazard changed shape — \
             re-read why the binding above exists before deleting either"
        );
    }

    #[test]
    fn save_as_preset_bound_to_cmd_shift_s() {
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(
            awase::Modifiers::CMD | awase::Modifiers::SHIFT,
            awase::Key::S,
        );
        assert_eq!(mgr.lookup(&hk), Some(Action::SaveSessionAsPreset));
    }

    #[test]
    fn layout_picker_bound_to_ctrl_l() {
        // Ctrl-L is RESERVED for the future layout picker (the
        // Ctrl-S-for-layouts analog). Today it resolves to a consumed
        // no-op so the keystroke no longer falls through to the shell
        // as 0x0c (which the shell renders as clear-screen).
        let mgr = KeybindManager::with_mado_defaults();
        let hk = awase::Hotkey::new(awase::Modifiers::CTRL, awase::Key::L);
        assert_eq!(mgr.lookup(&hk), Some(Action::LayoutPickerOpen));
    }

    #[test]
    fn layout_picker_action_name_round_trips() {
        assert_eq!(
            parse_action("layout_picker_open"),
            Some(Action::LayoutPickerOpen)
        );
        assert_eq!(
            parse_action("layout_picker"),
            Some(Action::LayoutPickerOpen)
        );
        assert_eq!(
            parse_action("layout_switcher"),
            Some(Action::LayoutPickerOpen)
        );
    }

    #[test]
    fn test_parse_action_known() {
        assert_eq!(parse_action("copy"), Some(Action::Copy));
        assert_eq!(parse_action("paste"), Some(Action::Paste));
        assert_eq!(
            parse_action("paste_from_selection"),
            Some(Action::PasteFromSelection)
        );
        assert_eq!(parse_action("scroll_to_top"), Some(Action::ScrollToTop));
        assert_eq!(parse_action("jump_to_prompt"), Some(Action::JumpToPrompt));
        assert_eq!(parse_action("clear_screen"), Some(Action::ClearScreen));
        assert_eq!(parse_action("select_all"), Some(Action::SelectAll));
        assert_eq!(
            parse_action("copy_url_to_clipboard"),
            Some(Action::CopyUrlToClipboard)
        );
        assert_eq!(
            parse_action("toggle_mouse_reporting"),
            Some(Action::ToggleMouseReporting)
        );
    }

    #[test]
    fn test_parse_action_aliases() {
        assert_eq!(parse_action("search"), Some(Action::SearchOpen));
        assert_eq!(
            parse_action("increase_font_size"),
            Some(Action::FontIncrease)
        );
        assert_eq!(
            parse_action("decrease_font_size"),
            Some(Action::FontDecrease)
        );
        assert_eq!(parse_action("reset_font_size"), Some(Action::FontReset));
        // Phase 4 — goto_split:* / close_surface resolve to None
        // (multiplexing belongs in tear).
        assert_eq!(parse_action("goto_split:next"), None);
        assert_eq!(parse_action("goto_split:previous"), None);
        assert_eq!(parse_action("close_surface"), None);
        assert_eq!(parse_action("reset"), Some(Action::ResetTerminal));
    }

    #[test]
    fn test_parse_action_unknown() {
        assert_eq!(parse_action("not_a_real_action"), None);
        assert_eq!(parse_action(""), None);
    }

    #[test]
    fn action_canonical_name_round_trips() {
        // Pin the derived as_str ↔ from_str_kind inverse: every
        // action's canonical name parses back to itself. Catches a
        // drifted #[kind(name = …)] that no longer agrees with the
        // serde snake_case spelling parse_action delegates to.
        let actions = [
            Action::Copy,
            Action::Paste,
            Action::PasteFromSelection,
            Action::ScrollUp,
            Action::ScrollDown,
            Action::ScrollPageUp,
            Action::ScrollPageDown,
            Action::ScrollToTop,
            Action::ScrollToBottom,
            Action::JumpToPrompt,
            Action::JumpToPromptPrev,
            Action::JumpToPromptNext,
            Action::SearchOpen,
            Action::SearchClose,
            Action::SearchNext,
            Action::SearchPrev,
            Action::DirPickerOpen,
            Action::SessionPickerOpen,
            Action::LayoutPickerOpen,
            Action::FontIncrease,
            Action::FontDecrease,
            Action::FontReset,
            Action::ResetTerminal,
            Action::ClearScreen,
            Action::ToggleFullscreen,
            Action::SelectAll,
            Action::CopyLastCommandOutput,
            Action::CopyUrlToClipboard,
            Action::ToggleMouseReporting,
        ];
        for action in actions {
            let name = action.as_str();
            assert_eq!(
                parse_action(name),
                Some(action),
                "{action:?} canonical name {name:?} failed round-trip",
            );
        }
    }

    // ── madori_key_to_pty_bytes coverage ─────────────────────────
    //
    // The block below pins the byte translation that BOTH the
    // legacy single-pane (`main.rs`) and embedded-tear
    // (`gui_tear_attach.rs`) input paths now share. The named
    // `ctrl_r_produces_0x12_via_helper` test is the dedicated
    // regression guard for the 2026-05-26 Ctrl-R bug — the
    // embedded-tear path used to drop every Ctrl+letter on the
    // floor before reaching the PTY.

    fn mods(ctrl: bool, alt: bool, shift: bool, meta: bool) -> madori::event::Modifiers {
        madori::event::Modifiers {
            ctrl,
            alt,
            shift,
            meta,
        }
    }

    #[test]
    fn ctrl_r_produces_0x12_via_helper() {
        // ─── REGRESSION GUARD ───────────────────────────────────
        // Pressing Ctrl-R in a mado window MUST produce the byte
        // 0x12 on the PTY so frostmourne's atuin/skim history
        // picker can fire. Before consolidation, the embedded-tear
        // path swallowed this keystroke. If this test fails, the
        // history picker is broken for every operator. Do not
        // weaken or delete it without an explicit replacement
        // assertion at the call site.
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(&key, &None, mods(true, false, false, false), false);
        assert_eq!(
            bytes.as_deref(),
            Some(&[0x12u8][..]),
            "Ctrl-R must produce 0x12 (DC2 / ^R) — frostmourne's history picker relies on it"
        );
    }

    #[test]
    fn every_ctrl_letter_produces_correct_control_byte() {
        // The 26 Ctrl+letter sequences MUST translate to 0x01..0x1A.
        // Anything else regresses readline / atuin / vim / etc.
        for (idx, letter) in ('a'..='z').enumerate() {
            let expected = (idx as u8) + 1;
            let key = madori::event::KeyCode::Char(letter);
            let bytes =
                madori_key_to_pty_bytes(&key, &None, mods(true, false, false, false), false);
            assert_eq!(
                bytes.as_deref(),
                Some(&[expected][..]),
                "Ctrl-{} should map to {:#04x} (got {:?})",
                letter,
                expected,
                bytes
            );
        }
    }

    #[test]
    fn ctrl_letter_via_text_branch_also_works() {
        // Some keyboard layouts surface Ctrl+letter as `text = Some("r")`
        // instead of `KeyCode::Char('r')` with empty text. Both shapes
        // must produce the same control byte.
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(
            &key,
            &Some("r".to_string()),
            mods(true, false, false, false),
            false,
        );
        assert_eq!(bytes.as_deref(), Some(&[0x12u8][..]));
    }

    #[test]
    fn alt_char_prepends_escape() {
        let key = madori::event::KeyCode::Char('b');
        let bytes = madori_key_to_pty_bytes(&key, &None, mods(false, true, false, false), false);
        assert_eq!(bytes.as_deref(), Some(&[0x1b, b'b'][..]));
    }

    #[test]
    fn alt_text_prepends_escape() {
        let key = madori::event::KeyCode::Char('b');
        let bytes = madori_key_to_pty_bytes(
            &key,
            &Some("b".to_string()),
            mods(false, true, false, false),
            false,
        );
        assert_eq!(bytes.as_deref(), Some(&[0x1b, b'b'][..]));
    }

    // ── kitty_encode_key coverage ────────────────────────────────
    //
    // The CSI-u encoder moved here from main.rs so the embedded-tear
    // path can share it. The test_kitty_* tests below moved with it
    // verbatim (suffix params are now u8); the kitty_* tests add the
    // coverage the move surfaced (super bit, modified arrows/F-keys,
    // shift-only fallback, combined modifier sums).

    #[test]
    fn test_kitty_key_seq_no_modifiers_u() {
        let seq = kitty_key_seq(97, 1, b'u');
        assert_eq!(seq, b"\x1b[97u");
    }

    #[test]
    fn test_kitty_key_seq_with_modifiers_u() {
        let seq = kitty_key_seq(97, 5, b'u');
        assert_eq!(seq, b"\x1b[97;5u");
    }

    #[test]
    fn test_kitty_key_seq_arrow_no_modifiers() {
        let seq = kitty_key_seq(1, 1, b'A');
        assert_eq!(seq, b"\x1b[A");
    }

    #[test]
    fn test_kitty_key_seq_arrow_with_modifiers() {
        let seq = kitty_key_seq(1, 5, b'A');
        assert_eq!(seq, b"\x1b[1;5A");
    }

    #[test]
    fn test_kitty_tilde_seq_no_modifiers() {
        let seq = kitty_tilde_seq(3, 1);
        assert_eq!(seq, b"\x1b[3~");
    }

    #[test]
    fn test_kitty_tilde_seq_with_modifiers() {
        let seq = kitty_tilde_seq(3, 5);
        assert_eq!(seq, b"\x1b[3;5~");
    }

    #[test]
    fn test_kitty_encode_no_flags_returns_none() {
        let m = madori::event::Modifiers::default();
        assert!(kitty_encode_key(&madori::event::KeyCode::Char('a'), &None, &m, 0).is_none());
    }

    #[test]
    fn test_kitty_encode_char_with_ctrl() {
        let m = mods(true, false, false, false);
        let result = kitty_encode_key(&madori::event::KeyCode::Char('a'), &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[97;5u"[..]));
    }

    #[test]
    fn test_kitty_encode_enter() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Enter, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[13u"[..]));
    }

    #[test]
    fn test_kitty_encode_char_no_modifiers_returns_none() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Char('x'), &None, &m, 1);
        assert!(
            result.is_none(),
            "plain char with no modifiers falls through to normal input"
        );
    }

    #[test]
    fn test_kitty_encode_f1() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::F(1), &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[P"[..]));
    }

    #[test]
    fn test_kitty_encode_arrow_up_with_shift() {
        let m = mods(false, false, true, false);
        let result = kitty_encode_key(&madori::event::KeyCode::Up, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[1;2A"[..]));
    }

    #[test]
    fn test_kitty_encode_tab() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Tab, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[9u"[..]));
    }

    #[test]
    fn test_kitty_encode_backspace() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Backspace, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[127u"[..]));
    }

    #[test]
    fn test_kitty_encode_escape() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Escape, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[27u"[..]));
    }

    #[test]
    fn test_kitty_encode_arrow_down() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Down, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[B"[..]));
    }

    #[test]
    fn test_kitty_encode_arrow_left() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Left, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[D"[..]));
    }

    #[test]
    fn test_kitty_encode_arrow_right() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Right, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[C"[..]));
    }

    #[test]
    fn test_kitty_encode_home() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Home, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[H"[..]));
    }

    #[test]
    fn test_kitty_encode_end() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::End, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[F"[..]));
    }

    #[test]
    fn test_kitty_encode_delete() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::Delete, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[3~"[..]));
    }

    #[test]
    fn test_kitty_encode_page_up() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::PageUp, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[5~"[..]));
    }

    #[test]
    fn test_kitty_encode_page_down() {
        let m = madori::event::Modifiers::default();
        let result = kitty_encode_key(&madori::event::KeyCode::PageDown, &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[6~"[..]));
    }

    #[test]
    fn test_kitty_encode_char_with_alt() {
        let m = mods(false, true, false, false);
        let result = kitty_encode_key(&madori::event::KeyCode::Char('a'), &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[97;3u"[..]));
    }

    #[test]
    fn test_kitty_encode_char_ctrl_shift() {
        let m = mods(true, false, true, false);
        let result = kitty_encode_key(&madori::event::KeyCode::Char('a'), &None, &m, 1);
        assert_eq!(result.as_deref(), Some(&b"\x1b[97;6u"[..]));
    }

    #[test]
    fn kitty_shift_only_char_falls_back_to_utf8() {
        // Level-1 disambiguate: shift alone is not "beyond shift" —
        // the char still goes as plain UTF-8.
        let key = madori::event::KeyCode::Char('a');
        let m = mods(false, false, true, false);
        assert_eq!(kitty_encode_key(&key, &None, &m, 1), None);
    }

    #[test]
    fn kitty_super_char_is_csi_u() {
        // meta (super) = bit 8 → modifier value 9.
        let key = madori::event::KeyCode::Char('a');
        let m = mods(false, false, false, true);
        let bytes = kitty_encode_key(&key, &None, &m, 1);
        assert_eq!(bytes.as_deref(), Some(&b"\x1b[97;9u"[..]));
    }

    #[test]
    fn kitty_modified_enter_is_csi_u() {
        let m = mods(true, false, false, false);
        let bytes = kitty_encode_key(&madori::event::KeyCode::Enter, &None, &m, 1);
        assert_eq!(bytes.as_deref(), Some(&b"\x1b[13;5u"[..]));
    }

    #[test]
    fn kitty_arrow_up_plain_and_ctrl() {
        let up = madori::event::KeyCode::Up;
        let plain = kitty_encode_key(&up, &None, &mods(false, false, false, false), 1);
        assert_eq!(plain.as_deref(), Some(&b"\x1b[A"[..]));
        let ctrl = kitty_encode_key(&up, &None, &mods(true, false, false, false), 1);
        assert_eq!(ctrl.as_deref(), Some(&b"\x1b[1;5A"[..]));
    }

    #[test]
    fn kitty_alt_tilde_key_carries_modifier() {
        let m = mods(false, true, false, false);
        let bytes = kitty_encode_key(&madori::event::KeyCode::PageUp, &None, &m, 1);
        assert_eq!(bytes.as_deref(), Some(&b"\x1b[5;3~"[..]));
    }

    #[test]
    fn kitty_modified_function_keys() {
        let m = mods(true, false, false, false);
        let f1 = kitty_encode_key(&madori::event::KeyCode::F(1), &None, &m, 1);
        assert_eq!(f1.as_deref(), Some(&b"\x1b[1;5P"[..]));
        let f5 = kitty_encode_key(&madori::event::KeyCode::F(5), &None, &m, 1);
        assert_eq!(f5.as_deref(), Some(&b"\x1b[15;5~"[..]));
    }

    #[test]
    fn kitty_combined_modifiers_sum_bits() {
        // ctrl(4) + shift(1) + alt(2) → 1 + 7 = 8.
        let key = madori::event::KeyCode::Char('x');
        let bytes = kitty_encode_key(&key, &None, &mods(true, true, true, false), 1);
        assert_eq!(bytes.as_deref(), Some(&b"\x1b[120;8u"[..]));
    }

    #[test]
    fn kitty_space_is_csi_u() {
        let m = madori::event::Modifiers::default();
        let bytes = kitty_encode_key(&madori::event::KeyCode::Space, &None, &m, 1);
        assert_eq!(bytes.as_deref(), Some(&b"\x1b[32u"[..]));
    }

    #[test]
    fn bare_cmd_returns_none_so_caller_can_drop() {
        // Cmd-X with no matching keybinding is a GUI shortcut, not
        // PTY input. Helper returns None — caller drops.
        let key = madori::event::KeyCode::Char('x');
        let bytes = madori_key_to_pty_bytes(
            &key,
            &Some("x".to_string()),
            mods(false, false, false, true),
            false,
        );
        assert_eq!(bytes, None);
    }

    #[test]
    fn ctrl_cmd_letter_still_produces_control_byte() {
        // If both Ctrl and Cmd are held (e.g. global shortcut
        // intent that includes Ctrl), the helper still emits the
        // Ctrl byte; the keybinding lookup at the call site is
        // what decides whether to consume vs forward.
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(&key, &None, mods(true, false, false, true), false);
        assert_eq!(bytes.as_deref(), Some(&[0x12u8][..]));
    }

    #[test]
    fn plain_text_passes_through() {
        let key = madori::event::KeyCode::Char('a');
        let bytes = madori_key_to_pty_bytes(
            &key,
            &Some("a".to_string()),
            mods(false, false, false, false),
            false,
        );
        assert_eq!(bytes.as_deref(), Some(&b"a"[..]));
    }

    #[test]
    fn shift_text_passes_through_uppercase() {
        // madori does OS-level composition so Shift+r arrives as text="R".
        let key = madori::event::KeyCode::Char('r');
        let bytes = madori_key_to_pty_bytes(
            &key,
            &Some("R".to_string()),
            mods(false, false, true, false),
            false,
        );
        assert_eq!(bytes.as_deref(), Some(&b"R"[..]));
    }

    #[test]
    fn named_keys_map_to_canonical_bytes() {
        let m = mods(false, false, false, false);
        let cases: &[(madori::event::KeyCode, &[u8])] = &[
            (madori::event::KeyCode::Enter, b"\r"),
            (madori::event::KeyCode::Backspace, b"\x7f"),
            (madori::event::KeyCode::Tab, b"\t"),
            (madori::event::KeyCode::Escape, b"\x1b"),
            (madori::event::KeyCode::Space, b" "),
            (madori::event::KeyCode::Delete, b"\x1b[3~"),
            (madori::event::KeyCode::PageUp, b"\x1b[5~"),
            (madori::event::KeyCode::PageDown, b"\x1b[6~"),
        ];
        for (key, expected) in cases {
            let bytes = madori_key_to_pty_bytes(key, &None, m, false);
            assert_eq!(
                bytes.as_deref(),
                Some(*expected),
                "named key {:?} should map to {:?}",
                key,
                expected
            );
        }
    }

    #[test]
    fn cursor_keys_normal_mode_emit_csi() {
        // DECCKM reset (default) → ESC [ <ch>
        let m = mods(false, false, false, false);
        for (key, ch) in [
            (madori::event::KeyCode::Up, b'A'),
            (madori::event::KeyCode::Down, b'B'),
            (madori::event::KeyCode::Right, b'C'),
            (madori::event::KeyCode::Left, b'D'),
            (madori::event::KeyCode::Home, b'H'),
            (madori::event::KeyCode::End, b'F'),
        ] {
            let bytes = madori_key_to_pty_bytes(&key, &None, m, false);
            assert_eq!(
                bytes.as_deref(),
                Some(&[0x1b, b'[', ch][..]),
                "cursor key {:?} in normal mode should emit ESC [ {}",
                key,
                ch as char
            );
        }
    }

    #[test]
    fn cursor_keys_application_mode_emit_ss3() {
        // DECCKM set → ESC O <ch>
        let m = mods(false, false, false, false);
        for (key, ch) in [
            (madori::event::KeyCode::Up, b'A'),
            (madori::event::KeyCode::Down, b'B'),
            (madori::event::KeyCode::Right, b'C'),
            (madori::event::KeyCode::Left, b'D'),
        ] {
            let bytes = madori_key_to_pty_bytes(&key, &None, m, true);
            assert_eq!(
                bytes.as_deref(),
                Some(&[0x1b, b'O', ch][..]),
                "cursor key {:?} in app mode should emit ESC O {}",
                key,
                ch as char
            );
        }
    }

    #[test]
    fn f_keys_map_to_xterm_sequences() {
        let m = mods(false, false, false, false);
        let cases: &[(u8, &[u8])] = &[
            (1, b"\x1bOP"),
            (2, b"\x1bOQ"),
            (3, b"\x1bOR"),
            (4, b"\x1bOS"),
            (5, b"\x1b[15~"),
            (6, b"\x1b[17~"),
            (7, b"\x1b[18~"),
            (8, b"\x1b[19~"),
            (9, b"\x1b[20~"),
            (10, b"\x1b[21~"),
            (11, b"\x1b[23~"),
            (12, b"\x1b[24~"),
        ];
        for (n, expected) in cases {
            let bytes = madori_key_to_pty_bytes(&madori::event::KeyCode::F(*n), &None, m, false);
            assert_eq!(
                bytes.as_deref(),
                Some(*expected),
                "F{} should map to {:?}",
                n,
                expected
            );
        }
    }

    #[test]
    fn unknown_key_with_no_text_returns_none() {
        // A keystroke that has no text and no name (e.g. media keys)
        // returns None so the call site can ignore it.
        let bytes = madori_key_to_pty_bytes(
            &madori::event::KeyCode::F(99),
            &None,
            mods(false, false, false, false),
            false,
        );
        // F(99) hits the F-key arm → f_key_escape returns an empty
        // Vec by design. Caller should treat empty-byte payload as
        // "ignore" semantically — that's preserved from the legacy
        // helper.
        assert_eq!(bytes.as_deref(), Some(&[][..]));
    }

    #[test]
    fn ctrl_non_letter_falls_through_to_text() {
        // Ctrl+] arrives as text="]" (or similar). The helper has no
        // ctrl-symbol mapping; it forwards the text as-is. That
        // preserves the legacy behaviour — terminal apps that want
        // ctrl-symbol handling read raw bytes via termios.
        let key = madori::event::KeyCode::Char(']');
        let bytes = madori_key_to_pty_bytes(
            &key,
            &Some("]".to_string()),
            mods(true, false, false, false),
            false,
        );
        assert_eq!(bytes.as_deref(), Some(&b"]"[..]));
    }

    // ── End-to-end regression: simulate the embedded-tear flow ──
    //
    // This test composes the keybind action lookup with the byte
    // helper exactly the way `gui_tear_attach.rs` does. It is the
    // canonical "the Ctrl-R bug cannot return" guard — if anyone
    // re-introduces a `meta || ctrl` drop guard in the tear path
    // without first calling `madori_key_to_pty_bytes`, this test
    // catches it at the unit level.

    #[test]
    fn embedded_tear_flow_ctrl_r_reaches_pty() {
        let manager = KeybindManager::with_mado_defaults();
        let event = madori::event::KeyEvent {
            key: madori::event::KeyCode::Char('r'),
            text: None,
            modifiers: mods(true, false, false, false),
            pressed: true,
        };

        // Step 1: keybind lookup. Ctrl-R has no default action —
        // so we MUST fall through to PTY translation.
        let action = manager.lookup_madori(&event);
        assert!(
            action.is_none(),
            "Ctrl-R must not have a default mado keybinding — \
             frostmourne owns it via skim+atuin"
        );

        // Step 2: byte translation. Must produce 0x12 (^R / DC2).
        let bytes = madori_key_to_pty_bytes(&event.key, &event.text, event.modifiers, false);
        assert_eq!(
            bytes.as_deref(),
            Some(&[0x12u8][..]),
            "Ctrl-R MUST be translated to 0x12 for frostmourne to receive it"
        );
    }

    #[test]
    fn embedded_tear_flow_bare_cmd_drops() {
        // The symmetric case: Cmd+letter with no matching binding
        // returns None so the call site can drop (don't leak the
        // bare letter to the PTY).
        let manager = KeybindManager::with_mado_defaults();
        let event = madori::event::KeyEvent {
            key: madori::event::KeyCode::Char('j'),
            text: Some("j".to_string()),
            modifiers: mods(false, false, false, true),
            pressed: true,
        };

        let action = manager.lookup_madori(&event);
        assert!(action.is_none(), "Cmd+J has no default binding");

        let bytes = madori_key_to_pty_bytes(&event.key, &event.text, event.modifiers, false);
        assert_eq!(
            bytes, None,
            "bare Cmd with no matching binding must NOT leak text to the PTY"
        );
    }

    #[test]
    fn embedded_tear_flow_arrow_keys_respect_decckm() {
        // Vim, less, htop, btop, etc. set DECCKM (CSI ? 1 h) on
        // alt-screen entry and reset it on exit. The embedded-tear
        // path queries `pane_cursor_keys_mode` and passes the result
        // here; this test pins that arrow-key encoding flips
        // correctly with that input.
        let event = madori::event::KeyEvent {
            key: madori::event::KeyCode::Up,
            text: None,
            modifiers: mods(false, false, false, false),
            pressed: true,
        };

        // Normal mode (DECCKM reset, shell at the prompt) → ESC [ A.
        let normal = madori_key_to_pty_bytes(&event.key, &event.text, event.modifiers, false);
        assert_eq!(
            normal.as_deref(),
            Some(&b"\x1b[A"[..]),
            "Up in normal mode must emit ESC [ A — bash prompt-history navigation depends on it"
        );

        // Application mode (DECCKM set, vim in alt-screen) → ESC O A.
        let app = madori_key_to_pty_bytes(&event.key, &event.text, event.modifiers, true);
        assert_eq!(
            app.as_deref(),
            Some(&b"\x1bOA"[..]),
            "Up in application mode must emit ESC O A — vim cursor-key handling depends on it"
        );
    }

    #[test]
    fn embedded_tear_flow_common_shell_chords_all_reach_pty() {
        // Pin the full set of shell control chords that the embedded-
        // tear path must forward. If any one of these regresses to
        // None, the corresponding shell behaviour breaks.
        let cases: &[(char, u8, &str)] = &[
            ('a', 0x01, "Ctrl-A: beginning-of-line"),
            ('b', 0x02, "Ctrl-B: backward-char"),
            ('c', 0x03, "Ctrl-C: SIGINT"),
            ('d', 0x04, "Ctrl-D: EOF"),
            ('e', 0x05, "Ctrl-E: end-of-line"),
            ('f', 0x06, "Ctrl-F: forward-char"),
            ('k', 0x0b, "Ctrl-K: kill-line"),
            ('l', 0x0c, "Ctrl-L: clear-screen"),
            ('n', 0x0e, "Ctrl-N: next-history"),
            ('p', 0x10, "Ctrl-P: prev-history"),
            ('r', 0x12, "Ctrl-R: history-search-backward / atuin"),
            ('u', 0x15, "Ctrl-U: kill-line-backward"),
            ('w', 0x17, "Ctrl-W: kill-word-backward"),
            ('z', 0x1a, "Ctrl-Z: SIGTSTP"),
        ];
        for (ch, expected, label) in cases {
            let event = madori::event::KeyEvent {
                key: madori::event::KeyCode::Char(*ch),
                text: None,
                modifiers: mods(true, false, false, false),
                pressed: true,
            };
            let bytes = madori_key_to_pty_bytes(&event.key, &event.text, event.modifiers, false);
            assert_eq!(
                bytes.as_deref(),
                Some(&[*expected][..]),
                "{} — Ctrl-{} must map to {:#04x}",
                label,
                ch,
                expected
            );
        }
    }
}
