//! OSC 22 — mouse pointer shape control.
//!
//! Terminals advertise "the shell / app wants the mouse pointer to
//! look like `<shape>`" via `ESC ] 22 ; <name> ST`. The shape names
//! are the CSS `cursor` property vocabulary (`text`, `pointer`,
//! `wait`, …) so web apps / TUIs that cross into the terminal can
//! reuse one dictionary. Ghostty, kitty, and foot all implement
//! this. Mado did not — this module fills the gap with a typed
//! enum instead of a free-form string so round-trips don't leak
//! unvalidated names into renderer code.
//!
//! The query form `ESC ] 22 ; ? ST` asks the terminal for the
//! currently-active shape; mado responds with `ESC ] 22 ; <name> ST`
//! echoing the typed value's canonical name.
//!
//! ## Why a typed enum
//!
//! Every terminal that ships OSC 22 parses the argument as a string
//! and passes it straight to the platform cursor API. That's
//! two-plus rounds of untyped string matching (parse → validate →
//! platform lookup) and every round can drift against the CSS spec.
//! The typed variant collapses the three matches into one and
//! gives the platform layer a pattern-matchable enum that can't
//! be misspelled.

use pleme_kindstr_derive::KindStr;

/// CSS `cursor`-style pointer shape. Round-trips through
/// [`Self::from_str_kind`] ↔ [`Self::as_str`] (derived by `KindStr`).
/// Unknown names decode to `None` so the caller distinguishes "shape is
/// `Default`" from "the sender asked for a shape we don't recognize".
///
/// The vocabulary mirrors the CSS Basic User Interface Level 3
/// cursor keyword set; mado supports the entries ghostty / kitty /
/// foot do. Adding a new variant is an app-renderer concern — the
/// VT layer doesn't care what the OS does with the name.
/// The `as_str` / `from_str_kind` pair below is generated by
/// `#[derive(KindStr)]` (the macro-farm paired round-trip derive) from the
/// per-variant `#[kind(name = "...")]` attrs — one authored CSS-name table
/// instead of two hand-kept inverse match arms. CSS keywords are
/// case-sensitive, so unknown / wrong-case names return `None`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, KindStr)]
pub enum PointerShape {
    /// Platform default pointer (typically an arrow).
    #[default]
    #[kind(name = "default")]
    Default,
    /// I-beam text caret. Set by editors / `less` over text.
    #[kind(name = "text")]
    Text,
    /// Link / clickable pointing hand.
    #[kind(name = "pointer")]
    Pointer,
    /// Spinning wait indicator — app is unresponsive.
    #[kind(name = "wait")]
    Wait,
    /// In-progress indicator — app is busy but still interactive.
    #[kind(name = "progress")]
    Progress,
    /// Precision crosshair — often used by graphics tools.
    #[kind(name = "crosshair")]
    Crosshair,
    /// Horizontal column-resize double-arrow.
    #[kind(name = "col-resize")]
    ColResize,
    /// Vertical row-resize double-arrow.
    #[kind(name = "row-resize")]
    RowResize,
    /// Generic move indicator (four-way arrow).
    #[kind(name = "move")]
    Move,
    /// Openhand — draggable area at rest.
    #[kind(name = "grab")]
    Grab,
    /// Closedhand — draggable area being dragged.
    #[kind(name = "grabbing")]
    Grabbing,
    /// Disabled / not-allowed slashed-circle.
    #[kind(name = "not-allowed")]
    NotAllowed,
    /// Help question-mark pointer.
    #[kind(name = "help")]
    Help,
    /// NW↔SE diagonal resize.
    #[kind(name = "nwse-resize")]
    NwseResize,
    /// NE↔SW diagonal resize.
    #[kind(name = "nesw-resize")]
    NeswResize,
    /// Horizontal bidirectional resize.
    #[kind(name = "ew-resize")]
    EwResize,
    /// Vertical bidirectional resize.
    #[kind(name = "ns-resize")]
    NsResize,
    /// Magnifier-plus.
    #[kind(name = "zoom-in")]
    ZoomIn,
    /// Magnifier-minus.
    #[kind(name = "zoom-out")]
    ZoomOut,
}

impl PointerShape {
    /// Every recognized variant. Useful for round-trip tests + the
    /// MCP tool that exposes the valid shape vocabulary to clients.
    #[must_use]
    #[allow(dead_code)] // Consumed by round-trip tests + pending MCP surface.
    pub fn all() -> &'static [PointerShape] {
        &[
            Self::Default,
            Self::Text,
            Self::Pointer,
            Self::Wait,
            Self::Progress,
            Self::Crosshair,
            Self::ColResize,
            Self::RowResize,
            Self::Move,
            Self::Grab,
            Self::Grabbing,
            Self::NotAllowed,
            Self::Help,
            Self::NwseResize,
            Self::NeswResize,
            Self::EwResize,
            Self::NsResize,
            Self::ZoomIn,
            Self::ZoomOut,
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_via_name_preserves_every_variant() {
        // For each variant, render it as a name, parse that name,
        // compare. Pins the from_name ↔ as_name inverse invariant.
        for variant in PointerShape::all() {
            let name = variant.as_str();
            let parsed = PointerShape::from_str_kind(name);
            assert_eq!(parsed, Some(*variant), "{name} failed round-trip");
        }
    }

    #[test]
    fn unknown_names_return_none() {
        assert!(PointerShape::from_str_kind("").is_none());
        assert!(PointerShape::from_str_kind("laser").is_none());
        // CSS is case-sensitive — mado must be too, otherwise
        // "POINTER" would silently match and round-trip to the
        // lowercase form.
        assert!(PointerShape::from_str_kind("POINTER").is_none());
    }

    #[test]
    fn every_name_is_lowercase_ascii_with_optional_hyphen() {
        // Keeps the vocabulary aligned with CSS without us hand-
        // typing each variant's acceptance. A typo in `as_name`
        // that introduces e.g. an underscore would trip this.
        for variant in PointerShape::all() {
            let name = variant.as_str();
            assert!(
                name.bytes()
                    .all(|b| b.is_ascii_lowercase() || b == b'-'),
                "{name} contains non-lowercase / non-hyphen chars",
            );
            assert!(!name.starts_with('-'), "{name} starts with hyphen");
            assert!(!name.ends_with('-'), "{name} ends with hyphen");
        }
    }

    #[test]
    fn default_resolves_to_default_variant() {
        // The #[default] attribute must line up with the "default"
        // CSS name — if that drifts, OSC 22 ; ? round-trips would
        // report something unexpected.
        let d = PointerShape::default();
        assert_eq!(d, PointerShape::Default);
        assert_eq!(d.as_str(), "default");
    }

    #[test]
    fn all_returns_canonical_count() {
        // Pin the variant count so adding a new variant needs a
        // conscious update (rather than slipping into the vocab
        // silently and getting missed by round-trip tests that
        // enumerate `::all()`).
        assert_eq!(PointerShape::all().len(), 19);
    }
}
